### ISSUE TITLE
ffmpeg exited with code 1: Failed to set value 'xxxx' for option 'ss': Option not found

### ISSUE THREAD

**Issue by crtl** [fluent-ffmpeg/node-fluent-ffmpeg#1029]
### Version information

* fluent-ffmpeg version: 2.1.1
* ffmpeg version: ffmpeg-static 4.2.5 on 
* OS: windows 10 Home 64 bit

### Code to reproduce

```typescript

/**
 Config:
{
        count: 1,
        folder: tmpdir,
        filename: thumbnailFileName,
    }
*/

export function generateVideoThumbnail(source: string, config: ffmpeg.ScreenshotsConfig): Promise<string[]> {

    if (!config.folder) {
        config.folder = os.tmpdir();
    }

    return new Promise((resolve, reject) => {
        let result: string[];

        ffmpeg(source)
            .on("filenames", (filenames: string[]) => {
                console.log("generateVideoThumbnail.onFilenames", filenames);
                //@ts-ignore
                result = filenames.map(filename => path.join(config.folder, filename));
            })
            .on("error", (error) => {
                console.log("generateVideoThumbnail.onError", error);
                reject(error);
            })
            .on("end", () => {
                console.log("generateVideoThumbnail.onEnd");
                resolve(result);
            })
            .screenshots(config);
    });
}

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
Thumbnails should be generated

### Observed results
```

generate thumbnails {
  thumbnailFileName: 'thumbnail_606908e7-94f0-45d2-9f6d-0e5376b3deb2.png'
}
generateVideoThumbnail.onFilenames [ 'thumbnail_606908e7-94f0-45d2-9f6d-0e5376b3deb2.png' ]
ffmpeg.start: ffmpeg -ss 16.6240665 -i C:\Users\User\AppData\Local\Temp\606908e7-94f0-45d2-9f6d-0e5376b3deb2.mp4 -y -filter_complex split=1[screen0] -vframes 1 -map [screen0] C:\Users\User\AppData\Local\Temp\thumbnail_606908e7-94f0-45d2-9f6d-0e5376b3deb2.png
error:  Error: ffmpeg exited with code 1: Failed to set value '16.6240665' for option 'ss': Option not found

    at ChildProcess.<anonymous> (D:\dev\backend\functions\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
ffmpeg.stdout:
ffmpeg.stderr:  ffprobe version 4.0.2 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180722
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Failed to set value '16.6240665' for option 'ss': Option not found

Error: ffmpeg exited with code 1: Failed to set value '16.6240665' for option 'ss': Option not found

    at ChildProcess.<anonymous> (D:\dev\backend\functions\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

```

The command generated is:
```
ffmpeg -ss 16.6240665 -i C:\Users\User\AppData\Local\Temp\606908e7-94f0-45d2-9f6d-0e5376b3deb2.mp4 -y -filter_complex split=1[screen0] -vframes 1 -map [screen0] C:\Users\User\AppData\Local\Temp\thumbnail_606908e7-94f0-45d2-9f6d-0e5376b3deb2.png
```

Running this in windows cmd is generating the thumbnail with following output:

```
D:\dev\backend\functions>D:\dev\backend\functions\node_modules\ffmpeg-static\ffmpeg.exe -ss 16.6240665 -i C:\Users\User\AppData\Local\Temp\606908e7-94f0-45d2-9f6d-0e5376b3deb2.mp4 -y -filter_complex split=1[screen0] -vframes 1 -map [screen0] C:\Users\User\AppData\Local\Temp\thumbnail_606908e7-94f0-45d2-9f6d-0e5376b3deb2.png
ffmpeg version git-2020-06-23-ce297b4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200621
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 55.100 / 56. 55.100
  libavcodec     58. 93.100 / 58. 93.100
  libavformat    58. 47.100 / 58. 47.100
  libavdevice    58. 11.100 / 58. 11.100
  libavfilter     7. 86.100 /  7. 86.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\User\AppData\Local\Temp\606908e7-94f0-45d2-9f6d-0e5376b3deb2.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2020-06-16T14:34:47.000000Z
    com.android.version: 10
    com.android.capture.fps: 30.000000
  Duration: 00:00:33.25, start: 0.000000, bitrate: 17267 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt470bg/smpte170m), 1920x1080, 17008 kb/s, SAR 1:1 DAR 16:9, 29.96 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 180
      creation_time   : 2020-06-16T14:34:47.000000Z
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -180.00 degrees
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      creation_time   : 2020-06-16T14:34:47.000000Z
      handler_name    : SoundHandle
Stream mapping:
  Stream #0:0 (h264) -> split
  split -> Stream #0:0 (png)
Press [q] to stop, [?] for help
[swscaler @ 000001e6ed80d7c0] **deprecated pixel format used, make sure you did set range correctly**
Output #0, image2, to 'C:\Users\User\AppData\Local\Temp\thumbnail_606908e7-94f0-45d2-9f6d-0e5376b3deb2.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.capture.fps: 30.000000
    com.android.version: 10
    encoder         : Lavf58.47.100
    Stream #0:0: Video: png, rgb24, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      encoder         : Lavc58.93.100 png
    Side data:
      displaymatrix: rotation of -0.00 degrees
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.0989x
video:2146kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

**Comment by crtl** [comment]
I found the solution:
You have to explicitly call `setFfmpegPath` amd `setFfprobePath` on the specific fluentffmpeg instance for it to have effect.
I called it globally.
On the other side there shouldnt be a static method when it has no effect.
