### ISSUE TITLE
Error initializing complex filters with valid FFmpeg command

### ISSUE THREAD

**Issue by vpanichkin** [fluent-ffmpeg/node-fluent-ffmpeg#1055]
### Version information

* fluent-ffmpeg version:
* ffmpeg version: N-98896-g0d46043
* OS: (Ubuntu 7.5.0-3ubuntu1~18.04)

### Error Description
The code generates valid `ffmpeg` code, but the node.js process fails with exception

### FFmpeg Code generated:
```
ffmpeg -i ./videos/1.webm -i ./videos/3.webm -i ./videos/4.webm -i ./videos/5.webm -y -filter_complex "[0:v] scale=qvga [a0];[1:v] scale=qvga [a1];[2:v] scale=qvga [a2];[3:v] scale=qvga [a3];[a0][a1][a2][a3]xstack=inputs=4:layout=0_0|w0_0|0_h0|w0_h0[out]" -map "[out]" -c:v libx264 -t '30'  ./server-generated.mkv
```

### Code to reproduce

```
const ffmpeg = require('fluent-ffmpeg');
ffmpeg.setFfmpegPath('/home/victor/bin/ffmpeg')
ffmpeg.setFfprobePath('/home/victor/bin/ffprobe')
const command = ffmpeg();
const fs = require('fs');
const path = require('path')

function recordCall(inputs) {
    inputs.forEach(input => {
        command.addInput(input);
    })
    command
        .complexFilter(generateComplexFilter(inputs.length))
        .outputOptions([
            '-map \"[out]\"',
            '-c:v libx264 -t \'30\' ',
        ])
        .save('./server-generated.mkv')
        .on('start', function(commandLine) {
            console.log(commandLine);
        })
        .on("error", function(er){
            console.log(er);
            console.log("error occured: "+er.message);
        })
        .on("end",function(){
            console.log("success");
        })
}

function generateComplexFilter(videosLength) {
    const filter = [];
    for (let i = 0; i < videosLength; i++) {
        filter.push(`[${i}:v] scale=qvga [a${i}];`)
    }
    filter.push(generateGrid(videosLength));
    return `"${filter.join("")}"`
}

function generateGrid(videosLength) {
    let gridParam = '';
    for (let i = 0; i < videosLength; i += 1) {
        gridParam += `[a${i}]`
    }
    gridParam += `xstack=inputs=${videosLength}:layout=`;
    let maximalElementsInRow;
    if (videosLength === 0 || videosLength === 1) {
        maximalElementsInRow = 1
    } else {
        maximalElementsInRow = Math.ceil(Math.sqrt(videosLength))
    }
    let columnsHeight = 0;
    while (videosLength > 0) {
        let elementsInCurrentRow = 0
        while (elementsInCurrentRow < maximalElementsInRow && videosLength) {
            gridParam += `${generateSum('w', 0, elementsInCurrentRow)}_${generateSum('h', 0, columnsHeight)}|`
            videosLength--;
            elementsInCurrentRow++;
        }
        columnsHeight += 1
    }
    gridParam = gridParam.slice(0, -1);
    gridParam += `[out]`
    return gridParam
}

function generateSum(prefix, from, to) {
    let sumString = ''
    for (let i = from; i < to; i++) {
        sumString += `${prefix}${i}+`
    }
    return sumString ? sumString.slice(0, -1) : '0';
}

recordCall([
    './videos/1.webm',
    './videos/3.webm',
    './videos/4.webm',
    './videos/5.webm',
])

module.exports = recordCall

```

### Expected results

FFmpeg executes without exception from Node.JS process

### Observed results

```
Error: ffmpeg exited with code 1: Error initializing complex filters.
Invalid argument

    at ChildProcess.<anonymous> (/home/victor/Documents/work/recorder_ws/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
error occured: ffmpeg exited with code 1: Error initializing complex filters.
Invalid argument
```

**Comment by vpanichkin** [comment]
Changed to this:


```
        .addOption('-filter_complex', generateComplexFilter(inputs.length))
        .addOption('-map', '[out]',)
        .addOption('-c:v', 'libx264')
        .addOption('-t', '30')
        .save('./server-generated.mkv')
```

Solved an issue. Closed

**Comment by vnicorici** [comment]
to fix quote problem add ffmpeg wrapper
ffmpeg.setFfmpegPath('./ffmpeg.wrapper.sh');

`#!/bin/bash
#echo $@ >> exec.cmd

cmd="/usr/local/bin/ffmpeg $@"
eval $cmd`
