### ISSUE TITLE
Complex filter works in command line, but not in javascript

### ISSUE THREAD

**Issue by tytremblay** [fluent-ffmpeg/node-fluent-ffmpeg#1057]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 4.1.0 (via [@ffmpeg-installer/ffmpeg](https://www.npmjs.com/package/@ffmpeg-installer/ffmpeg))
* OS: Ubuntu 18.04

### Code to reproduce

```js
const ffmpeg = FfmpegCommand(inputFile)
.addInputOption(`-ss ${startSeconds}`)
.addInput(preRollImage)
.addOutputOption(`-t ${durationSeconds}`)
.complexFilter(
          `"[1:v]scale=-1:720[scaled],
            [0:v][scaled]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2:enable='between(t,0,${preRollDuration})'"`
        )
.addOutputOptions([`-c:a copy`, `-c:v libx264 -preset veryfast`])
.output(`"${outputFile}"`).run();

```

This produces an `ffmpegCommand` that looks like:
```shell
ffmpeg -ss 605.710639 -i input.mp4 -i preRoll.png -y -filter_complex "[1:v]scale=-1:720[scaled],[0:v][scaled]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2:enable='between(t,0,5)'" -t 243 -c:a copy -c:v libx264 -preset veryfast "outputFile.mp4"
```

### Expected results
This command should scale `preRoll.png` to a height of 720, and overlay `preRoll.png` in the middle of `input.mp4` for a duration of 5 seconds.

If the generated command is printed from `fluent-ffmpeg` to the console, then copied to the terminal an executed (via the same ffmpeg executable), that's what happens.

### Observed results
```shell
Error: ffmpeg exited with code 1: Error initializing complex filters.
Invalid argument

    at ChildProcess.<anonymous> (/home/ty/frc/frc-video-splitter-3/app/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by imranswe** [comment]
Facing same issue. Command not being run by fluent-ffmpeg but when I copy and run it manually in a terminal it works fine.
