### ISSUE TITLE
An error occurred: spawn 

### ISSUE THREAD

**Issue by RailgunWinjoy** [fluent-ffmpeg/node-fluent-ffmpeg#1070]
I tried to convert the mp4 to hls and failed with the under error.
But the command line  ffmpeg -i D://tmp/test.mp4 -profile:v baseline -level 3.0 -s 640x360 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls index.m3u8  works.

`
     An error occurred: spawn C:\Program Files\ffmpeg-4.2.3 ENOENT Error: spawn C:\Program Files\ffmpeg-4.2.3 ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)

    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {

      errno: 'ENOENT',
     code: 'ENOENT',
      syscall: 'spawn C:\\Program Files\\ffmpeg-4.2.3',
      path: 'C:\\Program Files\\ffmpeg-4.2.3',
      spawnargs: [ '-formats' ]
     } undefined
`

And the code is 

  `     
      var fs = require('fs');
       var ffmpeg = require('fluent-ffmpeg');
       var command = ffmpeg();
       export function convertingVideo(file) {

       command.addInput('D://tmp/test.mp4').outputOptions([
            '-map 0:0',
            '-map 0:1',
            '-map 0:0',
            '-map 0:1',
            '-s:v:0 2160x3840',
            '-c:v:0 libx264',
            '-b:v:0 2000k',
            '-s:v:1 960x540',
            '-c:v:1 libx264',
            '-b:v:1 365k',
            // '-var_stream_map', '"v:0,a:0 v:1,a:1"',
            '-master_pl_name master.m3u8',
            '-f hls',
            '-max_muxing_queue_size 1024',
            '-hls_time 1',
            '-hls_list_size 0',
            '-hls_segment_filename', 'v%v/fileSequence%d.ts'
        ]).output('D://tmp/test/video.m3u8')
        .on('start', function(commandLine) {
            console.log('Spawned Ffmpeg with command: ' + commandLine);
        })
        .on('error', function(err, stdout, stderr) {
            console.log('An error occurred: ' + err.message, err, stderr);
        })
        .on('progress', function(progress) {
            console.log('Processing: ' + progress.percent + '% done')
        })
        .on('end', function(err, stdout, stderr) {
            console.log('Finished processing!' /*, err, stdout, stderr*/ )
        })
        .run()
     }`

Also i have created this two %FFMPEG_PATH and %FFPROBE_PATH in the environment variables and added them to the path

**Comment by mehulpurohit97** [comment]
I am also converting mp4 to hls using below code, it is working for me.

```
var fs = require('fs');
var ffmpeg = require('fluent-ffmpeg');

// open input stream
var infs = new ffmpeg()

infs.addInput('input.mp4').outputOptions([
    '-codec: copy',
    '-bsf:v h264_mp4toannexb',
    '-start_number 0',
    '-hls_time 10',
    '-hls_list_size 0',
    '-f hls'
]).output('./output.m3u8')
    .on('start', function (commandLine) {
        console.log('Spawned Ffmpeg with command: ' + commandLine);
    })
    .on('error', function (err, stdout, stderr) {
        console.log('An error occurred: ' + err.message, err, stderr);
    })
    .on('progress', function (progress) {
        console.log('Processing: ' + progress.percent + '% done')
    })
    .on('end', function (err, stdout, stderr) {
        console.log('Finished processing!' /*, err, stdout, stderr*/)
    })
    .run()
```

**Comment by SAUMYASINHA24** [comment]
is there any parameter that allows setting chunk duration fixed? say (10 secs)
