### ISSUE TITLE
Error during processing Error: ffmpeg exited with code 1: myapp/uploads/*.png: Function not implemented / Windows

### ISSUE THREAD

**Issue by facuescobar** [fluent-ffmpeg/node-fluent-ffmpeg#1130]
### Version information
* fluent-ffmpeg version:  "^2.1.2",
* ffmpeg version: "^0.0.4",
* OS: Windows 10

### Code to reproduce
**electron.js**
```js
const {
  BrowserWindow,
  app,
  ipcMain,
  dialog,
  Notification,
} = require("electron");
const path = require("path");
const fs = require("fs");
const isDev = require("electron-is-dev");

const { createTimelapse } = require("./app/video");

const { getPath, createFolder, emptyCreate } = require("./app/files");
const { createFrames, saveImageDataURL } = require("./app/images");
const { createTimelapse } = require("./app/video");

...

// video
ipcMain.on("create:video", (_, dir, fileName, dirUploads) => {
  return createTimelapse(
    `${getPath(dir)}/${fileName}`,
    `${getPath(dirUploads)}/*.png`,
    60
  )
    .then((e) => {
      dialog
        .showSaveDialog({
          title: "Select the File Path to save",
          defaultPath: path.join(__dirname, `/${fileName}`),
          buttonLabel: "Save",
          filters: [
            {
              name: "Text File",
              extensions: ["mov"],
            },
          ],
          properties: [],
        })
        .then((file) => {
          console.log(file.canceled);

          if (!file.canceled) {
            fs.copyFile(
              getPath(`${dir}/${fileName}`),
              file.filePath.toString(),
              (err) => {
                if (err) throw err;

                _.sender.send(
                  "notification:info",
                  "Web Font Render",
                  "Select a folder to save the video!"
                );
              }
            );
          }
        })
        .catch((err) => console.log(err));
    })
    .catch((e) => console.error(e));
});

```

**video.js**
```js
const ffmpeg = require("fluent-ffmpeg");

//Get the paths to the packaged versions of the binaries we want to use
const ffmpegPath = require("ffmpeg-static").replace(
  "app.asar",
  "app.asar.unpacked"
);
const ffprobePath = require("ffprobe-static").path.replace(
  "app.asar",
  "app.asar.unpacked"
);

ffmpeg.setFfmpegPath(ffmpegPath);
ffmpeg.setFfprobePath(ffprobePath);

// create time lapse
const createTimelapse = (output, inputFiles, fps = 60) => {
  return new Promise((resolve, reject) => {
    ffmpeg()
      .addInput(inputFiles)
      .inputOptions("-pattern_type glob") // allow the glob pattern
      .inputFPS(260)
      .noAudio()
      .outputOptions([`-r ${fps}`, `-pix_fmt yuv420p`])
      .videoCodec("libx264")
      .on("progress", (data) => {
        console.log("Frames completed:", data.frames);
      })
      .on("error", (err) => {
        console.error("Error during processing", err);
        reject(err);
      })
      .on("end", () => {
        console.log("Processing finished !");
        resolve("Processing finished");
      })
      .save(output);
  });
};

module.exports = {
  createTimelapse,
};
```

### App Functionality
- This code receives a list of png image paths to create a timelapse video, and we use ffmpeg() to create and export the video.

### Expected Results
- The application should display the dialog to save the video in an specific folder. 
- This works fine in the Mac version.

### Observed results
This error happens in Windows only. 

When export video commands are executed, the application should display the dialog to save the video. ​

But instead we get this error:
```
[1] Error during processing Error: ffmpeg exited with code 1: app/uploads/*.png: Function not implemented
[1]
[1]     at ChildProcess.<anonymous> (C:\Users\...user...\Downloads\fontrender\...project...\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
[1]     at ChildProcess.emit (events.js:310:20)
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[1] Error: ffmpeg exited with code 1: webFontApp/uploads/*.png: Function not implemented
[1]
[1]     at ChildProcess.<anonymous> (C:\Users\...user...\Downloads\fontrender\...project...\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
[1]     at ChildProcess.emit (events.js:310:20)
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

```

**app/uploads/*.png** is the directory path with the png files

**Comment by facuescobar** [comment]
I have tried to run this by command line and I it seems that globbing not supported.

``` 
C:\Users\...\Downloads\fontrender\...\...\uploads>ffmpeg -framerate 10 -pattern_type glob -i "*.png" -c:v libx264 -pix_fmt yuv420p out.mp4
ffmpeg version 2021-05-23-git-4c0d6c91f6-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  1.100 / 59.  1.100
  libavformat    59.  2.101 / 59.  2.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.101 /  8.  0.101
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[image2 @ 000000d5c5350640] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
*.png: Function not implemented

```

Any ideas if this is possible?
Thanks!

**Comment by facuescobar** [comment]
So, glob method is not implemented for windows, so I have changed my logic to use sequence mode (img-%3d.png).
