### ISSUE TITLE
false TypError [ERR_INVALID_ARG_TYPE] even tho I'm following the docs

### ISSUE THREAD

**Issue by ShaharBrandman** [fluent-ffmpeg/node-fluent-ffmpeg#1134]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: (using @ffmpeg-installer/ffmpeg 1.0.20)
* OS: Windows 10
* Node: 12

### Code to reproduce

```js
const ffmpeg = require('fluent-ffmpeg')
const ffmpegPath = require('@ffmpeg-installer/ffmpeg')
const fs = require('fs')
const ytdl = require('ytdl-core')

ffmpeg.setFfmpegPath(ffmpegPath)

async function get() {
    ffmpeg(await ytdl('LuchnQtK86U')).pipe(fs.createWriteStream('track.mp3'))
}

get()

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
the youtube video's audio should compressed into track.mp3

### Observed results 
the following error
```
(node:1) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:547:16)
    at /app/available_modules/1623080324000/fluent-ffmpeg/lib/processor.js:152:24
    at FfmpegCommand.proto._getFfmpegPath (/app/available_modules/1623080324000/fluent-ffmpeg/lib/capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (/app/available_modules/1623080324000/fluent-ffmpeg/lib/processor.js:132:10)
    at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (/app/available_modules/1623080324000/fluent-ffmpeg/lib/capabilities.js:517:10)
    at /app/available_modules/1623080324000/fluent-ffmpeg/lib/capabilities.js:568:14
    at nextTask (/app/available_modules/1623080324000/fluent-ffmpeg/node_modules/async/dist/async.js:4576:27)
    at Object.waterfall (/app/available_modules/1623080324000/fluent-ffmpeg/node_modules/async/dist/async.js:4587:9)
    at Object.awaitable [as waterfall] (/app/available_modules/1623080324000/fluent-ffmpeg/node_modules/async/dist/async.js:208:32)
    at FfmpegCommand.proto._checkCapabilities (/app/available_modules/1623080324000/fluent-ffmpeg/lib/capabilities.js:565:11)
    at /app/available_modules/1623080324000/fluent-ffmpeg/lib/processor.js:298:14
    at nextTask (/app/available_modules/1623080324000/fluent-ffmpeg/node_modules/async/dist/async.js:4576:27)
    at Object.waterfall (/app/available_modules/1623080324000/fluent-ffmpeg/node_modules/async/dist/async.js:4587:9)
    at Object.awaitable [as waterfall] (/app/available_modules/1623080324000/fluent-ffmpeg/node_modules/async/dist/async.js:208:32)
    at FfmpegCommand.proto._prepare (/app/available_modules/1623080324000/fluent-ffmpeg/lib/processor.js:295:11)
    at FfmpegCommand.proto.exec.proto.execute.proto.run (/app/available_modules/1623080324000/fluent-ffmpeg/lib/processor.js:431:10)
    at FfmpegCommand.proto.writeToStream.proto.pipe.proto.stream (/app/available_modules/1623080324000/fluent-ffmpeg/lib/recipes.js:64:34)
    at Object.get (/app/index.js:11:47)
```

### Checklist

* [ x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by ShaharBrandman** [comment]
nvm I just switched to working with ffmpeg, anyway.. it might be a problem with @ffmpeg-installer/ffmpeg
