### ISSUE TITLE
Error: Output stream closed when trying to stream an mp3 file with express

### ISSUE THREAD

**Issue by ShaharBrandman** [fluent-ffmpeg/node-fluent-ffmpeg#1135]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version:
* OS: Windows 10

### Code to reproduce

```js
const express = require('express')

const server = express()

const ffmpeg = require('fluent-ffmpeg')
ffmpeg.setFfmpegPath('ffmpeg.exe')

server.get('/', (req, res) => {
    res.set('Content-Type', 'audio/mp3')

    ffmpeg()
        .input('track.mp3')
        .toFormat('mp3')
        .pipe(res, { end: true })
});

```

### Expected results
track.mp3 to be streamed to the express server on root

### Observed results
```
Error: Output stream closed
    at Timeout._onTimeout (C:\Users\Shahar_2\Desktop\Projects\CUNTMUSIC-Server\node_modules\fluent-ffmpeg\lib\processor.js:491:25)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (C:\Users\Shahar_2\Desktop\Projects\CUNTMUSIC-Server\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at Timeout._onTimeout (C:\Users\Shahar_2\Desktop\Projects\CUNTMUSIC-Server\node_modules\fluent-ffmpeg\lib\processor.js:491:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

### Checklist

* [ ] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by ricfio** [comment]
The terminateTimeout option (PR https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/1292) could solve this issue.
