### ISSUE TITLE
Error: Cannot find ffmpeg on Azure Function

### ISSUE THREAD

**Issue by KelvinTseTR** [fluent-ffmpeg/node-fluent-ffmpeg#1275]
I am running fluent-ffmpeg on Azure Function App. It works when testing locally. However, when I run the code on Azure, it cannot read ffmpeg with the following error:

Error: Cannot find ffmpeg
    at /home/site/wwwroot/node_modules/fluent-ffmpeg/lib/processor.js:134:22
    at proto._getFfmpegPath (/home/site/wwwroot/node_modules/fluent-ffmpeg/lib/capabilities.js:90:14)
    at proto._spawnFfmpeg (/home/site/wwwroot/node_modules/fluent-ffmpeg/lib/processor.js:130:10)
    at proto.availableFormats.proto.getAvailableFormats (/home/site/wwwroot/node_modules/fluent-ffmpeg/lib/capabilities.js:517:10)
    at /home/site/wwwroot/node_modules/fluent-ffmpeg/lib/capabilities.js:568:14
    at fn (/home/site/wwwroot/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/home/site/wwwroot/node_modules/async/lib/async.js:498:34)
    at process.processImmediate (node:internal/timers:478:21)

### Version information
* fluent-ffmpeg version: 2.1.3
* ffmpeg version: 7.0
* OS: Linux

Anyone have the same trouble of implementing fleunt-ffmpeg on Azure and how do you resolve that?

**Comment by mithiridi** [comment]
@KelvinTseTR is there any solution for this ?
