### ISSUE TITLE
ReferenceError: `__dirname` is not defined

### ISSUE THREAD

**Issue by Stadly** [fluent-ffmpeg/node-fluent-ffmpeg#1283]
I cannot use `fluent-ffmpeg` in the production build of my SvelteKit app. It works in dev mode, and also in preview mode, but in the final production build, any call to `ffmpeg` results in a `ReferenceError: __dirname is not defined`. I guess it is an issue with ESM vs CommonJS.

### Version information

* fluent-ffmpeg version: 2.1.3
* ffmpeg version: 5.1.5
* OS: Alpine Linux (Windows Subsystem for Linux)

### Code to reproduce

```js
import ffmpeg from "fluent-ffmpeg";
ffmpeg();
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
No errors

### Observed results
```
ReferenceError: __dirname is not defined
    at new FfmpegCommand (file:///app/build/server/chunks/index-D6fKiITG.js:5210:69)
    at FfmpegCommand (file:///app/build/server/chunks/index-D6fKiITG.js:5178:13)
    at file:///app/build/server/chunks/0-DGpjmR_G.js:15:8
    at file:///app/build/server/chunks/server-DbC9RgP-.js:13:32
    at load_server_data (file:///app/build/server/chunks/index-B8KRwtQw.js:1464:42)
    at file:///app/build/server/chunks/index-B8KRwtQw.js:2947:24
```

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by moraxh** [comment]
Did you found a solution for this issue?

**Comment by Stadly** [comment]
I just defined if it is not defined:

```ts
global.__dirname = global.__dirname ?? "";
ffmpeg(bufferStream).ffprobe((error, data) => {
  // ...
});
```

Looking at the source code, setting `presets` to a non-empty string might also work:

```ts
ffmpeg(bufferStream, { presets: "dummy-path-to-prevent-use-of-__dirname" }).ffprobe((error, data) => {
  // ...
});
```

**Comment by Stadly** [comment]
I've created a PR to fix this: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/1319
