### ISSUE TITLE
 Error: spawn ELOOP

### ISSUE THREAD

**Issue by pdavid0** [fluent-ffmpeg/node-fluent-ffmpeg#370]
```
error: Sending 500 ("Server Error") response: 
 Error: spawn ELOOP
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34) { [Error: spawn ELOOP] code: 'ELOOP', errno: 'ELOOP', syscall: '
```

While using fluent-ffmpeg 1.7.2 on Ubuntu 12.04.5 LTS with 
ffmpeg version :

```
ffmpeg version 0.10.12-7:0.10.12-1~precise1 Copyright (c) 2000-2014 the FFmpeg developers
  built on Apr 26 2014 09:49:36 with gcc 4.6.3
  configuration: --arch=amd64 --disable-stripping --enable-pthreads --enable-runtime-cpudetect --extra-version='7:0.10.12-1~precise1' --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --enable-bzlib --enable-libdc1394 --enable-libfreetype --enable-frei0r --enable-gnutls --enable-libgsm --enable-libmp3lame --enable-librtmp --enable-libopencv --enable-libopenjpeg --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-vaapi --enable-vdpau --enable-libvorbis --enable-libvpx --enable-zlib --enable-gpl --enable-postproc --enable-libcdio --enable-x11grab --enable-libx264 --shlibdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-static
  libavutil      51. 35.100 / 51. 35.100
  libavcodec     53. 61.100 / 53. 61.100
  libavformat    53. 32.100 / 53. 32.100
  libavdevice    53.  4.100 / 53.  4.100
  libavfilter     2. 61.100 /  2. 61.100
  libswscale      2.  1.100 /  2.  1.100
  libswresample   0.  6.100 /  0.  6.100
  libpostproc    52.  0.100 / 52.  0.100
Hyper fast Audio and Video encoder
```
Code:
```
                new ffmpeg({
                        source: tmpVideo.videoFd
                    })
                    .withSize('960x540')
                    .on('error', function(err) {
                        if (err) {
                            console.log('An error occurred: ');
                            console.log(err);
                            // console.log(sterr);
                            // console.log(out);
                            // console.log("ffmpeg stdout:\n" + stdout);
                            return res.serverError(err);
                        }
                    })
                    .on('end', function(filenames) {
                        console.log('Successfully generated ' + filenames.join(', '));
                    })
                    .takeScreenshots({
                        count: 1,
                        filename: '%b'
                    }, thumbPath);
```

Wierd thing is that it works like a charm on my MBpro (Yosemite 10.10.2), ffmpeg :
```
ffmpeg version 2.5.2 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jan 23 2015 19:41:36 with Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --arch=x86_64 --enable-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
```

Any idea why ?

**Comment by njoyard** [comment]
That's weird indeed. Is thumbPath a symlink ? Is your 'end' handler called, and if so, what exactly does it output ? Or is the error simply thrown when calling .takeScreenshots  ?

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.
