### ISSUE TITLE
[Error: ffmpeg exited with code 1]

### ISSUE THREAD

**Issue by lsvx** [fluent-ffmpeg/node-fluent-ffmpeg#378]
Hi,

I just installed fluent-ffmpeg and cannot succeed converting a single file. I am using the following code: 
````javascript
var ffmpeg = require('fluent-ffmpeg');

ffmpeg('myvideo.m4v').
noVideo()
.audioCodec('libmp3lame')
.format('mp3')
.on('start', function(cmdline) {
    console.log('Command line: ' + cmdline);
})
.on('error', function(err, stdout, stderr) {
    console.log('err: ', err);
    console.log('ffmpeg stdout: ' + stdout);
    console.log('ffmpeg stderr: ' + stderr);
}).
output('myaudio.mp3').run()
````

The only output I get is:
````
err:  [Error: ffmpeg exited with code 1]
ffmpeg stdout: undefined
ffmpeg stderr: undefined
````

I can run the equivalent command in my terminal
````
ffmpeg -i myvideo.m4v -vn -f mp3 myaudio.mp3
````
or even more complex commands:
````
cat myvideo.m4v | ffmpeg -i pipe:0 -vn -f mp3 pipe:1 > myaudio.mp3
````
and they work fine.

I am running:
node v0.12.0
node-fluent-ffmpeg 2.0.0-rc3
ffmpeg 2.5.3 (installed with brew)
OS X 10.10.2

I git cloned the repository and installed the dependencies, but I am seeing nine tests fail when running `make test`:
````
  Capabilities
    ffmpeg capabilities
      1) should enable querying for available codecs
got error: Error: ffmpeg exited with code 1
    at ChildProcess.<anonymous> (/Users/lsvx/Code/node-fluent-ffmpeg/lib/processor.js:167:22)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
      2) should enable querying for available encoders
      3) should enable querying capabilities without instanciating a command
got error: Error: ffmpeg exited with code 1
    at ChildProcess.<anonymous> (/Users/lsvx/Code/node-fluent-ffmpeg/lib/processor.js:167:22)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
      4) should enable checking command arguments for available codecs and formats
    flvtool path
      5) should look for fflvtool in the PATH if FLVTOOL2_PATH is not defined
      - should use FLVTOOL2_PATH if defined and valid
      6) should fall back to searching in the PATH if FLVTOOL2_PATH is invalid
      7) should remember fflvtool path
  Processor
    Process controls
          [WARN] Invalid niceness value: 100, must be between -20 and 20
      8) should dynamically renice process
      9) "after each" hook: cleanup
````

Any idea what the issue may be?

**Comment by lsvx** [comment]
Fixed! It looks like the ffmpeg install was corrupt. To fix the issue, I uninstalled ffmpeg, eliminated all the shared and included libraries, and reinstalled the latest ffmpeg with brew.

**Comment by montanaflynn** [comment]
@lsvx I'm having the same problem with `ffmpeg 2.8.3` installed with homebrew. How did you go about removing the shared and included libraries? 

I noticed these three tests were failing:

```
 237 passing (21s)
  7 pending
  3 failing

  1) Capabilities flvtool path should look for fflvtool in the PATH if FLVTOOL2_PATH is not defined:
     Uncaught AssertionError: expected 0 to be above 0
      at Assertion.fail (node_modules/should/lib/assertion.js:91:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:160:19)
      at test/capabilities.test.js:567:32
      at lib/capabilities.js:267:9
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:1204:30
      at lib/capabilities.js:260:11
      at lib/utils.js:223:16
      at F (node_modules/which/which.js:78:16)
      at E (node_modules/which/which.js:82:29)
      at node_modules/which/which.js:93:16
      at FSReqWrap.oncomplete (fs.js:82:15)

  2) Capabilities flvtool path should fall back to searching in the PATH if FLVTOOL2_PATH is invalid:
     Uncaught AssertionError: expected 0 to be above 0
      at Assertion.fail (node_modules/should/lib/assertion.js:91:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:160:19)
      at test/capabilities.test.js:601:32
      at lib/capabilities.js:267:9
      at node_modules/async/lib/async.js:52:16
      at Immediate._onImmediate (node_modules/async/lib/async.js:1201:34)

  3) Capabilities flvtool path should remember fflvtool path:
     Uncaught AssertionError: expected 0 to be above 0
      at Assertion.fail (node_modules/should/lib/assertion.js:91:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:160:19)
      at test/capabilities.test.js:620:32
      at lib/capabilities.js:267:9
      at node_modules/async/lib/async.js:52:16
      at Immediate._onImmediate (node_modules/async/lib/async.js:1201:34)
```

**Comment by montanaflynn** [comment]
@lsvx actually for me everything was fixed by installing `flvmeta`

`brew install flvmeta`

**Comment by shashi87** [comment]
I am  getting this error "fmpeg exited with code 1: Filtergraph 'anullsrc' was specified through the -vf/-af/-filter option for output stream 0:1, which is fed from a complex filtergraph.
8|archive  | -vf/-af/-filter and -filter_complex cannot be used together for the same stream."  any Idea
