### ISSUE TITLE
Error: Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by BenBBear** [fluent-ffmpeg/node-fluent-ffmpeg#423]
When use filename as input and output, it works fine. But when use stream as input/output, error occurs.

ffmpeg version 2.6.2

```js
var ffmpeg = require('fluent-ffmpeg');
var convert = function(input, output) {
    var command = ffmpeg(input);

    command
        .videoCodec('libx264')
        .toFormat('mp4')
        .output(output)
        .on('end', function() {
            console.log('finish processing');
        })
        .run();    
};

var fs = require('fs');
var path = require('path');

var input_file_name = path.resolve('./xxx.mov');
var output_file_name = path.resolve('./xxx.mp4');
var input = fs.createReadStream(input_file_name);
var output = fs.createWriteStream(output_file_name);


convert(input_file_name, output_file_name);  // works fine

convert(input, output); // error
convert(input, output_file_name);  // error
/** error message
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ffmpeg exited with code 1: Output file #0 does not contain any stream
    at ChildProcess.<anonymous> (/path/to/node_modules/fluent-ffmpeg/lib/processor.js:167:22)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
**/


convert(input_file_name, output); // error
/** error message 
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

    at ChildProcess.<anonymous> (/path/to/node_modules/fluent-ffmpeg/lib/processor.js:167:22)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
**/

```

Any ideas to fix it?

**Comment by apptaminJb** [comment]
Try this:
```
var convert = function(input, output) {
  var command = ffmpeg(input);
  command.videoCodec('libx264').toFormat('mp4').on('end', function() {
    console.log('finish processing');
  }).pipe(output, {
    end: true
  });
};
```
And you should also add the bitrate to keep the same quality.
Cheers from France

**Comment by njoyard** [comment]
* **Always use an 'error' event handler**
* Please report errors according to the [contribution guide](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/CONTRIBUTING.md). As a side effect, it might also give you useful information about your problem...
* Do not use streams for both input and output. That's not something nodejs supports correctly.
* Never use streams when you can use filenames. That's just awful practice.

**Comment by elartix** [comment]
I have the same issue, appear when i try to add overlay image
`node-fluent v2.0.0`

`program.beginTime = 0`, 
`program.duration = 5 `

tested on this file `https://www.youtube.com/watch?v=UQgssgaZGBM`

```javascript
ffmpeg(stream)
.videoCodec('libx264')
.format('mp4')
.fps(program.fps)
.setStartTime(program.beginTime)
.duration(program.duration)
.input(wmimage)
.complexFilter([
	{
		filter: 'overlay',
		options: {x: 'W-w-10', y: 'H-h-10'},
		outputs: 'output'
  	}
], 'output')
.on('progress', progress)
.on('error', errorExporting)
.on('end', function () {

})
.save('./tmp/' + filename + '.mp4');
```

converting is succesfull but `'./tmp/' + filename + '.mp4'` is broken

**Comment by apptaminJb** [comment]
Did you check if your output file is empty? 
Did you open it with QuickTimePlayer? 
(Because you need to add a specific option if you want to be able to read it with QuickTimePlayer)

**Comment by elartix** [comment]
mp4 file with  this text

`    ftypisom   isomiso2avc1mp41   free   mdat   �moov   lmvhd              �                                                @                                 budta   Zmeta       !hdlr        mdirappl            -ilst   %�too   data       Lavf56.40.101`

**Comment by elartix** [comment]
commandLine on start ('fluent-ffmpeg')
```ffmpeg -ss 0 -i pipe:0 -i ./images/logo.png -y -filter_complex overlay=x=W-w-10:y=H-h-10[output] -map [output] -vcodec libx264 -r 15 -f mp4 -t 5 ./tmp/test.mp4```



Tried from terminal:
```ffmpeg -ss 0 -i ./tmp/test.mp4 -i ./images/logo.png -y -filter_complex overlay=x=W-w-10:y=H-h-10[output] -map [output] -vcodec libx264 -r 15 -f mp4 -t 5 ./tmp/testout.mp4```

Result is OK

```ffmpeg version N-74369-g55a07cf Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      54. 30.100 / 54. 30.100
  libavcodec     56. 57.100 / 56. 57.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 32.100 /  5. 32.100
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './tmp/test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:00:05.05, start: 0.046440, bitrate: 508 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 377 kb/s, 15 fps, 15 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Input #1, png_pipe, from './images/logo.png':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: png, rgba(pc), 154x56, 25 tbr, 25 tbn, 25 tbc
[libx264 @ 0x23d7ac0] using SAR=1/1
[libx264 @ 0x23d7ac0] using cpu capabilities: MMX2 SSE2Fast SSSE3 Cache64
[libx264 @ 0x23d7ac0] profile High, level 2.2
[libx264 @ 0x23d7ac0] 264 - core 142 r2491 24e4fed - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to './tmp/testout.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 640x360 [SAR 1:1 DAR 16:9], q=-1--1, 15 fps, 15360 tbn, 15 tbc (default)
    Metadata:
      encoder         : Lavc56.57.100 libx264
Stream mapping:
  Stream #0:0 (h264) -> overlay:main
  Stream #1:0 (png) -> overlay:overlay
  overlay -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
frame=   75 fps=0.0 q=-1.0 Lsize=     220kB time=00:00:04.86 bitrate= 370.4kbits/s dup=1 drop=0    
video:219kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.701129%
[libx264 @ 0x23d7ac0] frame I:1     Avg QP:22.59  size: 17601
[libx264 @ 0x23d7ac0] frame P:44    Avg QP:23.73  size:  3627
[libx264 @ 0x23d7ac0] frame B:30    Avg QP:27.02  size:  1530
[libx264 @ 0x23d7ac0] consecutive B-frames: 37.3% 24.0% 12.0% 26.7%
[libx264 @ 0x23d7ac0] mb I  I16..4:  9.0% 46.1% 44.9%
[libx264 @ 0x23d7ac0] mb P  I16..4:  3.2%  7.9%  3.6%  P16..4: 20.6% 11.0%  3.8%  0.0%  0.0%    skip:49.9%
[libx264 @ 0x23d7ac0] mb B  I16..4:  0.5%  1.0%  0.7%  B16..8: 23.6%  8.0%  1.6%  direct: 1.2%  skip:63.6%  L0:47.6% L1:42.5% BI: 9.9%
[libx264 @ 0x23d7ac0] 8x8 transform intra:52.3% inter:67.9%
[libx264 @ 0x23d7ac0] coded y,uvDC,uvAC intra: 49.1% 52.8% 19.5% inter: 10.3% 11.3% 0.8%
[libx264 @ 0x23d7ac0] i16 v,h,dc,p: 36% 30%  8% 26%
[libx264 @ 0x23d7ac0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 16% 26%  4%  4%  5%  4%  7%  5%
[libx264 @ 0x23d7ac0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 40% 16% 13%  4%  5%  6%  5%  6%  3%
[libx264 @ 0x23d7ac0] i8c dc,h,v,p: 48% 16% 30%  6%
[libx264 @ 0x23d7ac0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x23d7ac0] ref P L0: 72.1% 13.8%  9.8%  4.3%
[libx264 @ 0x23d7ac0] ref B L0: 91.6%  8.0%  0.3%
[libx264 @ 0x23d7ac0] ref B L1: 98.6%  1.4%
[libx264 @ 0x23d7ac0] kb/s:356.95```

**Comment by apptaminJb** [comment]
It looks like it's coming from your stream, try with a file instead of a stream it should work.

**Comment by njoyard** [comment]
Closing this because it has not had any activity for months. Feel free to reopen if you still have issues/questions :)

**Comment by ximus** [comment]
thanks for the answers so far

> Do not use streams for both input and output. That's not something nodejs supports correctly.

I am new to node and very curious about this point. Any chance you could expand, or point me to other literature on the topic?

**Comment by davidgatti** [comment]
Just to be clear, the input must be a path to the file, you don't have to open the file with `fs`.
