### ISSUE TITLE
I have the libfdk acc audio codec installed but it still complains

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#432]
```
    Error: Audio codec libfdk_aac is not available
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/fluent-ffmpeg/lib/capabilities.js:634:21
        at fn (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:717:34)
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:1170:16
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:172:37
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:677:43
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:173:37
        at Immediate._onImmediate (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:1163:34)
        at processImmediate [as _immediateCallback] (timers.js:371:17)
```

And here evidence that it's installed:

```
$ dpkg -l | grep libfdk
libfdk-aac-dev:amd64                                 0.1.3-1                                                            amd64        Fraunhofer FDK AAC Codec Library - development files
libfdk-aac0:amd64                                    0.1.3-1                                                            amd64        Fraunhofer FDK AAC Codec Library - runtime files
```

**Comment by njoyard** [comment]
That's an ffmpeg issue. Having the libs installed does not mean ffmpeg can use them. You should see with the ffmpeg community how to fix that specific issue !

**Comment by binarykitchen** [comment]
alright, peace out

**Comment by binarykitchen** [comment]
http://stackoverflow.com/questions/30456371/audiocodec-doesnt-recognize-aac-or-libfdk-aac/32192296#32192296
