### ISSUE TITLE
TypeError: Ffmpeg.getAvailableEncoders is not a function

### ISSUE THREAD

**Issue by xerox95** [fluent-ffmpeg/node-fluent-ffmpeg#455]
Copied from demo:
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/README.md#querying-ffmpeg-capabilities

TypeError: Ffmpeg.getAvailableEncoders is not a function
    at Object.<anonymous> (/home/marc/NetBeansProjects/ffmpeg/ffmpeg.js:14:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3

NodeJS version: 4.1.2
ffmpeg version: 2.5.8-0
System: Ubuntu x64 15.04.1

**Comment by njoyard** [comment]
Yup, documentation is not up to date

**Comment by njoyard** [comment]
Oh and by the way, those are still callable on _instances_ of fluent-ffmpeg, just not on the constructor.
