### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by pietrop** [fluent-ffmpeg/node-fluent-ffmpeg#471]
having issues when initialising `var command = ffmpeg();`

```javascript
± node
> var ffmpeg = require('fluent-ffmpeg');
undefined
> var command = ffmpeg();
TypeError: Cannot read property 'source' of undefined
    at FfmpegCommand (/Users/pietropassarelli/code/apps/QUICKQUOTE_NODE/quickQuoteNode/node_modules/fluent-ffmpeg/lib/fluent-ffmpeg.js:17:20)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
> 
```

Any ideas on what could be the issue?

**Comment by njoyard** [comment]
You're using an outdated version.
Either update to version 2.x or use the proper constructor syntax for 1.x (see the documentation on that branch).
