### ISSUE TITLE
Filter error is not passed onto the error handler

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#477]
In my case ffmpeg throws following error

```
    ffmpeg exited with code 1: Output pad "default" with type audio of
the filter instance "Parsed_anull_0" of anull not connected to any
destination
    Error opening filters!
   
    --
    Error: ffmpeg exited with code 1: Output pad "default" with type
audio of the filter instance "Parsed_anull_0" of anull not connected to
any destination
    Error opening filters!
   
        at ChildProcess.<anonymous>
(/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/fluent-ffmpeg/lib/processor.js:167:22)
        at emitTwo (events.js:87:13)
        at ChildProcess.emit (events.js:172:7)
        at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
```

This uncaught error does not seem to be passed onto the `.on('error', function() {...});` handler. But it should be. A possible bug?

**Comment by njoyard** [comment]
Might be. Can you please show the offending code?

**Comment by binarykitchen** [comment]
I found out, I passed on an invalid audio frequency of `-1` - wish your tool had complained about it. Could you add that to validation?

**Comment by njoyard** [comment]
Fluent-ffmpeg does close to no validation to ffmpeg parameters. We let ffmpeg do that (because otherwise we would have to follow ffmpeg changes very closely). You have to examine error messages to get those errors.

Anyway, if an exception is thrown without going to the 'error' handler, that's a bug, but I would need your code to have a reproduction scenario.

**Comment by binarykitchen** [comment]
Good point re validation. All good then.

Exactly. Exception is thrown without going to the error handler. All you have to do is to use an invalid audio frequency of `-1`. Try it yourself.

But if you insist, here is the long command I used:
```
ffmpeg -r 15.251101979467286 -f image2 -thread_queue_size 64 -i ./frames/%d.webp -i ./videomail_preview.wav -y -acodec aac -strict experimental -ar -1 -ac 1 -vcodec libx264 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -crf 16 -preset fast -profile:v baseline -pix_fmt yuv420p -loglevel warning -movflags faststart ./videomail_good.mp4 -acodec libvorbis -ar -1 -ac 1 -vcodec libvpx -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -crf 8 -deadline good -cpu-used 1 -pix_fmt yuv420p -loglevel warning -movflags faststart ./videomail_good.webm
```

**Comment by njoyard** [comment]
Thanks, I'll have a look at it.
