### ISSUE TITLE
ffprobe : TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by piercus** [fluent-ffmpeg/node-fluent-ffmpeg#491]
Testing mp4 file here :
https://drive.google.com/file/d/0B60j0yzReyQccVJyeldqTXVHWW8/view?usp=sharing

Testing code is 

    var ffmpeg = require("fluent-ffmpeg");
    ffmpeg.ffprobe('test.mp4');

Result 

    > TypeError: Cannot convert undefined or null to object
        at Function.keys (native)
        at /home/pierre/dev/monteur/node_modules/fluent-ffmpeg/lib/ffprobe.js:153:40
        at Array.forEach (native)
        at handleExit (/home/pierre/dev/monteur/node_modules/fluent-ffmpeg/lib/ffprobe.js:152:46)
        at ChildProcess.<anonymous> (/home/pierre/dev/monteur/node_modules/fluent-ffmpeg/lib/ffprobe.js:190:11)
        at emitTwo (events.js:87:13)
        at ChildProcess.emit (events.js:172:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

On the command line

    ffprobe -show_streams -show_format test.mp4

Result

    ffprobe version 2.8 Copyright (c) 2007-2015 the FFmpeg developers
      built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
      configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
      libavutil      54. 31.100 / 54. 31.100
      libavcodec     56. 60.100 / 56. 60.100
      libavformat    56. 40.101 / 56. 40.101
      libavdevice    56.  4.100 / 56.  4.100
      libavfilter     5. 40.101 /  5. 40.101
      libavresample   2.  1.  0 /  2.  1.  0
      libswscale      3.  1.101 /  3.  1.101
      libswresample   1.  2.101 /  1.  2.101
      libpostproc    53.  3.100 / 53.  3.100
    Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
      Metadata:
        major_brand     : isom
        minor_version   : 512
        compatible_brands: isomiso2avc1mp41
        encoder         : Lavf56.40.101
      Duration: 00:00:01.00, start: 0.014000, bitrate: 581 kb/s
        Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 13361 kb/s, 30.01 fps, 30.01 tbr, 90k tbn, 180k tbc (default)
        Metadata:
          rotate          : 90
          handler_name    : VideoHandler
        Side data:
          displaymatrix: rotation of -90.00 degrees
        Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 125 kb/s (default)
        Metadata:
          handler_name    : SoundHandler
    [STREAM]
    index=0
    codec_name=h264
    codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
    profile=High
    codec_type=video
    codec_time_base=1/180000
    codec_tag_string=avc1
    codec_tag=0x31637661
    width=1920
    height=1080
    coded_width=1920
    coded_height=1088
    has_b_frames=0
    sample_aspect_ratio=0:1
    display_aspect_ratio=0:1
    pix_fmt=yuv420p
    level=40
    color_range=N/A
    color_space=unknown
    color_transfer=unknown
    color_primaries=unknown
    chroma_location=left
    timecode=N/A
    refs=1
    is_avc=1
    nal_length_size=4
    id=N/A
    r_frame_rate=90000/2999
    avg_frame_rate=90000/2999
    time_base=1/90000
    start_pts=89910
    start_time=0.999000
    duration_ts=2999
    duration=0.033322
    bit_rate=13361653
    max_bit_rate=N/A
    bits_per_raw_sample=8
    nb_frames=1
    nb_read_frames=N/A
    nb_read_packets=N/A
    DISPOSITION:default=1
    DISPOSITION:dub=0
    DISPOSITION:original=0
    DISPOSITION:comment=0
    DISPOSITION:lyrics=0
    DISPOSITION:karaoke=0
    DISPOSITION:forced=0
    DISPOSITION:hearing_impaired=0
    DISPOSITION:visual_impaired=0
    DISPOSITION:clean_effects=0
    DISPOSITION:attached_pic=0
    TAG:rotate=90
    TAG:language=eng
    TAG:handler_name=VideoHandler
    [SIDE_DATA]
    side_data_type=Display Matrix
    side_data_size=36
    displaymatrix=
    00000000:            0       65536           0
    00000001:       -65536           0           0
    00000002:            0           0  1073741824

    rotation=-90
    [/SIDE_DATA]
    [/STREAM]
    [STREAM]
    index=1
    codec_name=aac
    codec_long_name=AAC (Advanced Audio Coding)
    profile=LC
    codec_type=audio
    codec_time_base=1/48000
    codec_tag_string=mp4a
    codec_tag=0x6134706d
    sample_fmt=fltp
    sample_rate=48000
    channels=2
    channel_layout=stereo
    bits_per_sample=0
    id=N/A
    r_frame_rate=0/0
    avg_frame_rate=0/0
    time_base=1/48000
    start_pts=672
    start_time=0.014000
    duration_ts=48128
    duration=1.002667
    bit_rate=125944
    max_bit_rate=128000
    bits_per_raw_sample=N/A
    nb_frames=47
    nb_read_frames=N/A
    nb_read_packets=N/A
    DISPOSITION:default=1
    DISPOSITION:dub=0
    DISPOSITION:original=0
    DISPOSITION:comment=0
    DISPOSITION:lyrics=0
    DISPOSITION:karaoke=0
    DISPOSITION:forced=0
    DISPOSITION:hearing_impaired=0
    DISPOSITION:visual_impaired=0
    DISPOSITION:clean_effects=0
    DISPOSITION:attached_pic=0
    TAG:language=eng
    TAG:handler_name=SoundHandler
    [/STREAM]
    [FORMAT]
    filename=test.mp4
    nb_streams=2
    nb_programs=0
    format_name=mov,mp4,m4a,3gp,3g2,mj2
    format_long_name=QuickTime / MOV
    start_time=0.014000
    duration=1.003000
    size=72925
    bit_rate=581655
    probe_score=100
    TAG:major_brand=isom
    TAG:minor_version=512
    TAG:compatible_brands=isomiso2avc1mp41
    TAG:encoder=Lavf56.40.101
    [/FORMAT]

The output has a line break in

    [SIDE_DATA]
    side_data_type=Display Matrix
    side_data_size=36
    displaymatrix=
    00000000:            0       65536           0
    00000001:       -65536           0           0
    00000002:            0           0  1073741824

    rotation=-90
    [/SIDE_DATA]

So the parser quit.

**Comment by piercus** [comment]
duplicated with #460 .. already fixed
