### ISSUE TITLE
Output format avfoundation is not available

### ISSUE THREAD

**Issue by lobor** [fluent-ffmpeg/node-fluent-ffmpeg#492]
Hi,
I try to get a live stream of my cam with node-fluent-ffmpeg.

With this code i have this error

```javascript
var command = ffmpeg()
		.addOption('-f', 'avfoundation')
		.addOption('-video_device_index', 2)
		.addOption('-i', '"default"')
		.pipe(res, {end:true});
```

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Output format avfoundation is not available
    at /Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/lib/capabilities.js:585:21
    at fn (/Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:741:34)
    at /Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:1208:16
    at /Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:166:37
    at /Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:701:43
    at /Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:167:37
    at /Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:1204:30
    at /Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/lib/capabilities.js:545:7
    at handleExit (/Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/lib/processor.js:155:11)
    at ChildProcess.<anonymous> (/Applications/MAMP/htdocs/detect_cam/node_modules/fluent-ffmpeg/lib/processor.js:169:11)
```

I am on mac

Thanks

**Comment by njoyard** [comment]
Your ffmpeg version does not support avfoundation format, that's all there is to it.

**Comment by Maksims** [comment]
Did same, got same error.
But running ffmpeg from command line using same arguments - works.

**Comment by njoyard** [comment]
That's pretty weird. Can you post the output of `ffmpeg -formats` please?

**Comment by Maksims** [comment]
I'm afraid my raspberry had too much reinstalls since, and doing different things now, so wont be able to provide feedback on that one :(

**Comment by njoyard** [comment]
No problem, I'll test that with a different device type, should get the same results. Thanks for answering :)

**Comment by pOxaes** [comment]
Hi, I am having exactly the same issue.

I don't see this issue resolved (nor link to an other issue) so I'll add what I am facing.

Running ffmpeg from command line using same arguments works well, but not with fluent-ffmpeg.

command line:
`ffmpeg -f avfoundation -r 30 -s 640x480  -i "default" -vframes 1 output.jpg`

Node:
```
ffmpeg()
                .input('default')
                .inputFormat('avfoundation')
                .inputOptions('-r 30 -s 640x480')
                .outputOptions('-vframes 1')
                .output('output.jpg')
                .run()
```

avfoundation is in `ffmpeg -formats`:
`D  avfoundation    AVFoundation input device`

Here `ffmpeg -devices`

```
ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-vda
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Devices:
 D. = Demuxing supported
 .E = Muxing supported
 --
 D  avfoundation    AVFoundation input device
 D  lavfi           Libavfilter virtual input device
 D  qtkit           QTKit input device
```

Thanks!

**Comment by pOxaes** [comment]
A quick update because it is always solved once you have reported the issue... I just cleaned my node modules and reinstalled it... and it works well.

It's still weird, I'll come back to you if I reproduce it!

**Comment by arambekverdyan** [comment]
Hi @pOxaes 
I've the same problem with avfoundation:
Error: Output format avfoundation is not available

Ffmpeg installed on my OS X is support avfoundation but it can't muxe. And there are some check in fluent-ffmpeg package in compatibilities.js file (Its check for is the format supported and can it muxe) otherwise its throws error.

And now i can't compile my ffmpeg with avfoundation mux support
