### ISSUE TITLE
Encode torrent video on the fly

### ISSUE THREAD

**Issue by CocoJr** [fluent-ffmpeg/node-fluent-ffmpeg#499]
Hi,

First, congratz for your module ! It's very powerfull !

But, i can't encode video file from torrent to re-stream encoded video ....

I use torrent-stream. I download the video file in torrent and i want to encode into flv format to read it with my browser.

My line:

ffmpeg(file.createReadStream(range)).outputFormat('flv').outputOptions(['-ar 44100']).pipe(response);

I send it to http server. Without FFMPEG, i can view the video in my browser (but only when it's correctly encoded ...)

The error:

Error: Output stream closed

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Output stream closed
    at null._onTimeout (/..../fluent-ffmpeg/lib/processor.js:481:25)
    at Timer.listOnTimeout (timers.js:119:15)

Have you an hack for this ?

Thx a lot man.

**Comment by njoyard** [comment]
Hi,
See [this FAQ entry](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ#output-stream-closed) :)

**Comment by CocoJr** [comment]
Thanks for tout fait response :)If i understand, i juste need to add the options:
command.outputOption('-movflags frag_keyframe+faststart')
Thanks for your help, i trying this later :)

-------- Message d'origine --------
De : Nicolas Joyard <notifications@github.com> 
Date : 18/02/2016  09:02  (GMT+01:00) 
À : fluent-ffmpeg/node-fluent-ffmpeg <node-fluent-ffmpeg@noreply.github.com> 
Cc : Coco <thibaultcolette06@hotmail.fr> 
Objet : Re: [node-fluent-ffmpeg] Encode torrent video on the fly (#499) 

Hi,

See this FAQ entry :)

**Comment by njoyard** [comment]
I don't know of a way to bypass the 2 requests. And you cannot control what every client in the world will do. You just have to ensure your app is resilient, that is it can still continue working properly even when this error occured.
