### ISSUE TITLE
Error with mergeToFile()

### ISSUE THREAD

**Issue by ariestav** [fluent-ffmpeg/node-fluent-ffmpeg#505]
Getting an error when I user .mergeToFile().

> Error: ffmpeg exited with code 1: Argument 'B:\auto.avi' provided as input filename, but 'B:\dyn.avi' was already specified.

When I write my ._inputs property of the ffmpeg object I see:

```
[ { source: 'B:\\dyn.avi',
    isFile: true,
    isStream: false,
    options:
     { [Function]
       clear: [Function],
       get: [Function],
       find: [Function],
       remove: [Function],
       clone: [Function] } },
  { source: 'B:\\auto.avi',
    isFile: true,
    isStream: false,
    options:
     { [Function]
       clear: [Function],
       get: [Function],
       find: [Function],
       remove: [Function],
       clone: [Function] } },
  { source: 'B:\\easy.avi',
    isFile: true,
    isStream: false,
    options:
     { [Function]
       clear: [Function],
       get: [Function],
       find: [Function],
       remove: [Function],
       clone: [Function] } },
  { source: 'B:\\punc.avi',
    isFile: true,
    isStream: false,
    options:
     { [Function]
       clear: [Function],
       get: [Function],
       find: [Function],
       remove: [Function],
       clone: [Function] } } ]
```

Why is fluent-ffmpeg throwing that error?  I'm not doing *exactly* what's in the sample code because I'm using `.mergeAdd(filename) in a loop.  After the loop, I want to do the merge, but it doesn't work.  Any ideas?

**Comment by njoyard** [comment]
Can you please post your code ? And what's passed to the 'start' event ?

**Comment by ariestav** [comment]
```
ffmpeg              = require('fluent-ffmpeg');
concat_output       = "C:\\test-concat.avi",
ffmpeg_cmd          = ffmpeg();

ffmpeg_cmd.input("C:\\test\\test_FINAL_1080P_goog_dyn.avi");
ffmpeg_cmd.input("C:\\test\\test_FINAL_1080P_goog_auto.avi");;

ffmpeg_cmd.on('start', (command) => {
  console.log('Spawned FFmpeg with command: ' + command);
})

ffmpeg_cmd.on('error', (err) => {
    console.log("FFMPEG ERR: " + err.message);
    console.log(err.stack);
})

ffmpeg_cmd.on('end', (stdout, err) => {
    console.log("Job Finished!");
})

ffmpeg_cmd.videoCodec('libx264').noAudio();

console.log(ffmpeg_cmd._inputs);
ffmpeg_cmd.mergeToFile(concat_output);
```

Here's the output when I added the 'start' event:

```
Spawned FFmpeg with command: ffmpeg -i C:\test\test_FINAL_1080P_goog_dyn.avi -i C:\test\test_FINAL_1080P_goog_auto.avi -y -filter_complex concat=n=2:v=1:a=0 -an -vcodec libx264 C:\Arie\test-concat.avi
FFMPEG ERR: ffmpeg exited with code 1: Argument 'C:\test\test_FINAL_1080P_goog_auto.avi' provided as input filename, but 'C:\test\test_FINAL_1080P_goog_dyn.avi' was already specified.

Error: ffmpeg exited with code 1: Argument 'C:\test\test_FINAL_1080P_goog_auto.avi' provided as input filename, but 'C:\test\test_FINAL_1080P_goog_dyn.avi' was already specified.
```

Any ideas what I'm missing?  I thought maybe it was due to a space in a path or something, but alas, even without spaces I'm getting this error.

Thanks for your help.

**Comment by ariestav** [comment]
Also, if I remove one of the inputs so it results in one here are my results:

```
Spawned FFmpeg with command: ffmpeg -f avi -i C:\test\test_FINAL_1080P_goog_dyn.avi -y -filter_complex
concat=n=1:v=1:a=0 -an -vcodec libx264 -pix_fmt yuv420p C:\test\test-concat.avi

FFMPEG ERR: ffmpeg exited with code 1: Failed to set value '-filter_complex' for option 'y': Option not found

Error: ffmpeg exited with code 1: Failed to set value '-filter_complex' for option 'y': Option not found

    at ChildProcess.<anonymous> (L:\event-scripts\node_modules\fluent-ffmpeg\lib\processor.js:167:22)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
Any idea what the issue might be?

Thanks,
Arie

**Comment by ariestav** [comment]
Found the issue.  It was something I totally overlooked.  I decided to use absolute paths to the ffmpeg binaries, so I actually had this at the top of my file:

```
ffmpeg.setFfmpegPath("C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe");
ffmpeg.setFfmpegPath("C:\\Program Files\\ffmpeg\\bin\\ffprobe.exe");
```

Which should have been
```
ffmpeg.setFfmpegPath("C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe");
ffmpeg.setFfprobePath("C:\\Program Files\\ffmpeg\\bin\\ffprobe.exe");
```
Once I changed the method in the second line.  It worked! 

Closing the issue.

**Comment by njoyard** [comment]
Oh ! So it was calling ffprobe instead... :)

**Comment by sohwitt** [comment]
Thanks @ariestav for giving the solution, i did the same silly mistake. You saved a lot of my time and effort.
Cheers.

**Comment by muanziri** [comment]
Error ffmpeg exited with code 4294967274: frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
Conversion failed!

**Comment by muanziri** [comment]
any help
