### ISSUE TITLE
ffmpeg runs command fine manually but fails within nodejs

### ISSUE THREAD

**Issue by wpsmith** [fluent-ffmpeg/node-fluent-ffmpeg#515]
I have a nodejs module built upon fluent-ffmpeg (current available [codecs](https://gist.github.com/wpsmith/89dc73d814e1fb7c47aa#file-available-codecs-js), [encoders](https://gist.github.com/wpsmith/89dc73d814e1fb7c47aa#file-available-encoders-js), [filters](https://gist.github.com/wpsmith/89dc73d814e1fb7c47aa#file-available-filters-js), & [formats](https://gist.github.com/wpsmith/89dc73d814e1fb7c47aa#file-available-formats-js)). 

Here is the [module]https://gist.github.com/wpsmith/ce4e26270b457ea1313a#file-ffmpeg-test-js and [test](https://gist.github.com/wpsmith/ce4e26270b457ea1313a#file-test-js). The output is:
```
07:57 40s 509ms [Info]      [NOVA] 	 Adding file soft, lot.mp3
/absolute/path/to/folder/with/files/lot.mp3
file exists, adding
07:57 40s 513ms [Info]      [NOVA] 	 Adding file jimcond, current_delay.mp3
/absolute/path/to/folder/with/files/current_delay.mp3
07:57 40s 514ms [Info]      [NOVA] 	 Adding file jimfct, fct_delay.mp3
/absolute/path/to/folder/with/files/fct_delay.mp3
[start] Spawned Ffmpeg with command: ffmpeg -i /absolute/path/to/folder/with/files/lot.mp3 -y -filter_complex '[0:a]volume=1.0[soft];[soft]amix=inputs=1:duration=longest' -vn -loglevel debug /absolute/path/to/folder/with/files/out.aac
07:57 40s 550ms [Info]      [NOVA] 	 [error] An error occurred: ffmpeg exited with code 1: Error: ffmpeg exited with code 1:
    at ChildProcess.<anonymous> (/home/ubuntu/PROJECT/node_modules/fluent-ffmpeg/lib/processor.js:167:22)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
------------------------------------DEBUG:
	{ tmpDirPath: '/absolute/path/to/folder/with/files' }
----------------------------------------|
```

But when I run the command `ffmpeg -i /absolute/path/to/folder/with/files/lot.mp3 -y -filter_complex '[0:a]volume=1.0[soft];[soft]amix=inputs=1:duration=longest' -vn -loglevel debug /absolute/path/to/folder/with/files/out.aac` manually, it works (using this code change #514).

Output:
```
ffmpeg version N-63893-gc69defd Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul 16 2014 05:38:01 with gcc 4.6 (Debian 4.6.3-1)
  configuration: --prefix=/root/ffmpeg-static/64bit --extra-cflags='-I/root/ffmpeg-static/64bit/include -static' --extra-ldflags='-L/root/ffmpeg-static/64bit/lib -static' --extra-libs='-lxml2 -lexpat -lfreetype' --enable-static --disable-shared --disable-ffserver --disable-doc --enable-bzlib --enable-zlib --enable-postproc --enable-runtime-cpudetect --enable-libx264 --enable-gpl --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-gray --enable-libass --enable-libfreetype --enable-libopenjpeg --enable-libspeex --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-version3 --enable-libvpx
  libavutil      52. 89.100 / 52. 89.100
  libavcodec     55. 66.101 / 55. 66.101
  libavformat    55. 43.100 / 55. 43.100
  libavdevice    55. 13.101 / 55. 13.101
  libavfilter     4.  8.100 /  4.  8.100
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
Splitting the commandline.
Reading option '-i' ... matched as input file with argument '/absolute/path/to/folder/with/files/lot.mp3'.
Reading option '-y' ... matched as option 'y' (overwrite output files) with argument '1'.
Reading option '-filter_complex' ... matched as option 'filter_complex' (create a complex filtergraph) with argument '[0:a]volume=1.0[soft];[soft]amix=inputs=1:duration=longest'.
Reading option '-vn' ... matched as option 'vn' (disable video) with argument '1'.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Reading option '/absolute/path/to/folder/with/files/out.aac' ... matched as output file.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option y (overwrite output files) with argument 1.
Applying option filter_complex (create a complex filtergraph) with argument [0:a]volume=1.0[soft];[soft]amix=inputs=1:duration=longest.
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input file /absolute/path/to/folder/with/files/lot.mp3.
Successfully parsed a group of options.
Opening an input file: /absolute/path/to/folder/with/files/lot.mp3.
[mp3 @ 0x24b8900] Format mp3 probed with size=16384 and score=51
[mp3 @ 0x24b8900] id3v2 ver:3 flags:00 len:6576
[mp3 @ 0x24b8900] Before avformat_find_stream_info() pos: 6586 bytes read:65664 seeks:2
[mp3 @ 0x24b8900] max_analyze_duration 5000000 reached at 5015510 microseconds
[mp3 @ 0x24b8900] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x24b8900] After avformat_find_stream_info() pos: 129466 bytes read:163968 seeks:2 frames:194
Input #0, mp3, from '/absolute/path/to/folder/with/files/lot.mp3':
  Metadata:
    genre           : Blues
  Duration: 00:00:40.29, start: 0.000000, bitrate: 192 kb/s
    Stream #0:0, 194, 1/14112000: Audio: mp3, 44100 Hz, stereo, s16p, 192 kb/s
Successfully opened the file.
Parsing a group of options: output file /absolute/path/to/folder/with/files/out.aac.
Applying option vn (disable video) with argument 1.
Successfully parsed a group of options.
Opening an output file: /absolute/path/to/folder/with/files/out.aac.
detected 16 logical cores
[Parsed_volume_0 @ 0x24c9120] Setting 'volume' to value '1.0'
[Parsed_amix_1 @ 0x24c9c00] Setting 'inputs' to value '1'
[Parsed_amix_1 @ 0x24c9c00] Setting 'duration' to value 'longest'
[graph 0 input from stream 0:0 @ 0x24ca360] Setting 'time_base' to value '1/44100'
[graph 0 input from stream 0:0 @ 0x24ca360] Setting 'sample_rate' to value '44100'
[graph 0 input from stream 0:0 @ 0x24ca360] Setting 'sample_fmt' to value 's16p'
[graph 0 input from stream 0:0 @ 0x24ca360] Setting 'channel_layout' to value '0x3'
[graph 0 input from stream 0:0 @ 0x24ca360] tb:1/44100 samplefmt:s16p samplerate:44100 chlayout:0x3
[audio format for output stream 0:0 @ 0x24cc140] Setting 'sample_fmts' to value 's16'
[audio format for output stream 0:0 @ 0x24cc140] Setting 'sample_rates' to value '96000|88200|64000|48000|44100|32000|24000|22050|16000|12000|11025|8000|7350'
Successfully opened the file.
[Parsed_volume_0 @ 0x24c9120] auto-inserting filter 'auto-inserted resampler 0' between the filter 'graph 0 input from stream 0:0' and the filter 'Parsed_volume_0'
[audio format for output stream 0:0 @ 0x24cc140] auto-inserting filter 'auto-inserted resampler 1' between the filter 'Parsed_amix_1' and the filter 'audio format for output stream 0:0'
[AVFilterGraph @ 0x24b7f40] query_formats: 5 queried, 6 merged, 6 already done, 0 delayed
[auto-inserted resampler 0 @ 0x24ccb20] ch:2 chl:stereo fmt:s16p r:44100Hz -> ch:2 chl:stereo fmt:flt r:44100Hz
[auto-inserted resampler 0 @ 0x24ccb20] tb:0.000023 sample_rate:44100.000000 nb_channels:2.000000
[Parsed_volume_0 @ 0x24c9120] n:nan t:nan pts:nan precision:float volume:1.000000 volume_dB:0.000000
[Parsed_amix_1 @ 0x24c9c00] inputs:1 fmt:flt srate:44100 cl:stereo
[auto-inserted resampler 1 @ 0x24a76a0] ch:2 chl:stereo fmt:flt r:44100Hz -> ch:2 chl:stereo fmt:s16 r:44100Hz
Output #0, adts, to '/absolute/path/to/folder/with/files/out.aac':
  Metadata:
    genre           : Blues
    encoder         : Lavf55.43.100
    Stream #0:0, 0, 1/90000: Audio: aac (libvo_aacenc), 44100 Hz, stereo, s16, 128 kb/s
    Metadata:
      encoder         : Lavc55.66.101 libvo_aacenc
Stream mapping:
  Stream #0:0 (mp3) -> volume
  amix -> Stream #0:0 (libvo_aacenc)
Press [q] to stop, [?] for help
[output stream 0:0 @ 0x24cbde0] EOF on sink link output stream 0:0:default.
No more output streams to write to, finishing.
[libvo_aacenc @ 0x24cb960] Trying to remove 704 more samples than there are in the queue
size=     627kB time=00:00:40.08 bitrate= 128.1kbits/s
video:0kB audio:627kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Input file #0 (/absolute/path/to/folder/with/files/lot.mp3):
  Input stream #0:0 (audio): 1534 packets read (960284 bytes); 1534 frames decoded (1767168 samples);
  Total: 1534 packets (960284 bytes) demuxed
Output file #0 (/absolute/path/to/folder/with/files/out.aac):
  Output stream #0:0 (audio): 1726 frames encoded (1767168 samples); 1728 packets muxed (641985 bytes);
  Total: 1728 packets (641985 bytes) muxed
1534 frames successfully decoded, 0 decoding errors
[AVIOContext @ 0x24ca400] Statistics: 0 seeks, 1728 writeouts
[AVIOContext @ 0x24b8020] Statistics: 993308 bytes read, 2 seeks
```

So why does it fail within the nodejs module and not via the command line?

**Comment by wpsmith** [comment]
There is a problem with #514, fixed.

**Comment by njoyard** [comment]
So I think you got it, but I'll explain it again anyway :)

Basically the problem is "launching an executable with parameters" and "running a command from the shell" are *not* the same things. Your shell has control characters that have a special meaning for it (eg `;` that separates commands, hence your error), and should be escaped or quoted if you actually want to pass them to the program. This limitation does not exist when launching a program using system calls.

The only issue here is that what the 'start' event reports as a command line cannot be used directly in a shell. But it's only intended as a debug helper, not as something directly usable in a shell (that would be fixable, but there may be caveats for shells with weird quoting mechanisms).

**Comment by MikeGJennings** [comment]
I'm using the node.js `spawn` command (on a Mac), and encountering something similar. When I use the `-report` option in ffmpeg, the resulting log file shows the ffmpeg command at the top, and you can see that what's happening is that it's escaping the quotes, which messes up `-filter_complex` (in my case):

For example, before parameterization it may have this:
`-filter_complex "[0]volume=-3dB[u]; [1]volume=0dB[n]; [u][n] amix=inputs=2"`
But after, ffmpeg gets this:
`-filter_complex "\"[0]volume=-3dB[u];" "[1]volume=0dB[n];" "[u][n]" "amix=inputs=2\""`

Putting the whole `filter_complex` arg as one parameter line made it worse, as it encapsulated everything separated by spaces in quotes.  I've tried all kinds of stuff, `execFile()` does the same thing, even tried environment variables, but ultimately I gave up and reimplemented it with `fluent-ffmpeg`.
