### ISSUE TITLE
Error when using -filter

### ISSUE THREAD

**Issue by jeanres** [fluent-ffmpeg/node-fluent-ffmpeg#519]
Hi,

I am executing the following command

```
ffmpeg -i /tmp/3fd7c430-f5bc-11e5-82a0-fd37cbe56ffe.mp4 -y -filter:v "select=gte(n\,60)" -frames:v 1 -s 800x600 -f image2 test.png
```

The code snippet
```
ffmpeg(tempAssetFileName).addOptions([
  '-filter:v \"select=gte(n\\,60)\"',
  '-frames:v 1',
  '-s 800x600',
  '-f image2'
])
.on('start', function(commandLine) {
  console.log(commandLine);
}).output('test.png')
.run();
```
The commandLine logged can be executed via in the shell correctly but, the code returns the following

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: Error opening filters!
    at ChildProcess.<anonymous> (/Users/jeanre/Work/critique-compositor/node_modules/fluent-ffmpeg/lib/processor.js:168:22)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by njoyard** [comment]
Hello,

Please add a handler for the 'error' event, you'll probably find the reason why it is failing in one of its 3 arguments. Also, avoid passing a full command line as addOptions, this is not what fluent-ffmpeg is for, use dedicated methods instead.
