### ISSUE TITLE
Doesn't accept appending write streams

### ISSUE THREAD

**Issue by inspiredtolive** [fluent-ffmpeg/node-fluent-ffmpeg#606]
### What?

Passing an appending write stream, `fs.createWriteStream(filePath, { flags: 'a' })`, as an output doesn't seem to work.

### The code I tried to run
```
const stream = require('stream');
let bufferReadStream = new stream.PassThrough();
bufferReadStream.end(Buffer.concat(largeChunk));

ffmpeg(bufferReadStream)
.format('mp3')
.output(fs.createWriteStream(filePath, { flags: 'a' }))
.on('end', () => {
  console.log('formatting finished!');
})
.on('error', err => {
  console.log('format buffer error: ', err);
})
 .run();
```

### What I expected to happen and what actually happened

I was uploading an audio stream to node which is accepted as an array of buffers. I tried to avoid writing to disk and then converting it into an mp3 file so I tried to directly turn my buffers into an mp3. The code successfully runs the first time, creating an mp3 file, but after the 2nd time, it throws an error instead of appending it to the existing mp3 file.

```
format buffer error:  Error: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input

    at ChildProcess.<anonymous> (/Users/inspiredtolive/Desktop/HackReactor/Picky-Notes/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by inspiredtolive** [comment]
After some rigorous testing, I noticed that the first chunk of audio recording data is significantly larger than the 2nd chunk. This leads me to believe that the first chunk has some metadata, perhaps like 'this is the beginning of the recording', and you cannot split up an audio recording into separate mp3 files since the subsequent chunks do not have that metadata.

Is there another approach I can take to solving my problem?

**Comment by njoyard** [comment]
Looks like an ffmpeg issue ; I guess if you tried to do the same on command line it would fail as well. I think ffmpeg needs some kind of metadata on each call, and if you pass a raw audio chunk it does not know how to deal with it. Maybe you could use a single command, with a simple output file, and keep appending chunks to the input passthough stream.

Beware of using streams both for input and output, though. nodejs event loop will eventually deadlock on those.

**Comment by inspiredtolive** [comment]
Yea, I thought of that, but at that point, I'd rather write to audio file to disk then format than to keep the audio data in memory.
