### ISSUE TITLE
Using `amovie=[filepath]:loop=[numLoops]` in Winders

### ISSUE THREAD

**Issue by swampthang** [fluent-ffmpeg/node-fluent-ffmpeg#656]
I updated your awesome library today and now my loop audio setup is breaking in Windows (pronounced Wind-ers here in the South ;-). This is an Electron app. 

I snagged the latest FFMPEG and FFPROBE static binaries from [here](http://evermeet.cx/ffmpeg/). Does work in Mac. It actually broke in Mac until I ran a rebuild. Rebuilding in Windows didn't fix it.

First of all, the way the FFMPEG docs tell you to loop audio is the way I've been doing it and it has worked passing that input string as the input until now. It still works in command line when I test there. When that broke I tried using (like if I was gonna loop an audio file out to 1 min and 22 sec)...
```
ffmpeg({}).loop(1.22)
          .addInput(filepath)
```
But it errors saying the input is undefined. 

Here's what works and has been working in Mac:
```
function createCompositeAudio(data) {

// variables declared above

  if ( data.numLoops > 0 ) {
    inputStr = `amovie=${data.filepath}:loop=${data.numLoops}`;
  } else {
    inputStr = data.filepath;
  }

  var proc = new ffmpeg();

  // I do have some other callbacks that log some stuff in progress, etc but removed them here

  proc.addInput(inputStr)
  .on('error', function(error,stdout,stderr) {
      /// error handling
      console.log('error: ',error);
      console.log('stdout: ',stdout);
      console.log('stderr: ',stderr);
  })
  .addInputOption('-f lavfi')
  .addOutputOption('-y')
  .output(`${tempFolder}temp.wav`)
  .run();
}
```
In windows, first thing it complains about is the inputStr (var from the script above). Here's the log/error ouput (replaced user name with 'usr'):
```
----- inputStr:  amovie=C:\Users\usr\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav:loop=2
C:\Users\usr\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:131 error:  Error: ffmpeg exited with code 1: amovie=C:\Users\usr\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav:loop=2: No such file or directory
    at ChildProcess.<anonymous> (C:\Users\usr\Documents\kinetic-text-animator\build\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
So, I removed the loop and just put the input file to see what would happen and it complained about the lavfi filter...
```
error:  Error: ffmpeg exited with code 1: C:\Users\usr\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav: Invalid argument

    at ChildProcess.<anonymous> (C:\Users\usr\Documents\kinetic-text-animator\build\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
C:\Users\usr\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:132
Uncaught ReferenceError: stddout is not defined
```
When I commented out the filter it works but, of course, no loop.

Any help you can give on this is greatly appreciated. Thanks again for this awesome npm wrapper for FFMPEG!

**Comment by swampthang** [comment]
Tried the following and works in Mac but still getting errors on PC (left in the onStart and end callbacks):

```
function createCompositeAudio(data) {

  data.tempAudioFile = `${tempFolder}temp.wav`; // stick a temp.wav file in here.

  var bgSettings = data.bgSettings,
      proc = new ffmpeg(data.filepath);

  if ( data.numLoops > 0 && bgSettings.loopBg ) {
    proc.videoFilter('-lavfi');
    proc.addOption('-filter_complex', `amovie=${data.filepath}:loop=${data.numLoops}`);
  } 

  proc.on('start', function(ffmpegCommand) {
      console.log(`started compositing ${tempFolder}temp.wav`);
  })
  .on('end', function() {
      console.log(`ended compositing ${tempFolder}temp.wav`);
  })
  .on('error', function(error,stdout,stderr) {
      console.log('error: ',error);
      console.log('stdout', stdout);
      console.log('stderr', stderr);
  })
  .addOutputOption('-y')
  .output(`${tempFolder}temp.wav`)
  .run();
}
```
On PC I get this...
```
error:  Error: ffmpeg exited with code 1: Error initializing complex filters.
No such file or directory


    at ChildProcess.<anonymous> (C:\Users\carvel\Documents\kinetic-text-animator\build\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
C:\Users\carvel\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:129 stddout
C:\Users\carvel\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:130 stderr ffmpeg version N-83280-gcba4f0e Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 45.100 / 55. 45.100
  libavcodec     57. 75.100 / 57. 75.100
  libavformat    57. 65.100 / 57. 65.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 71.100 /  6. 71.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'C:\Users\carvel\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav':
  Duration: 00:00:15.34, bitrate: 1416 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
[Parsed_amovie_0 @ 000000000254b620] Failed to avformat_open_input 'C'
[AVFilterGraph @ 0000000002556340] Error initializing filter 'amovie' with args 'C:UserscarvelAppDataRoamingkinetictextanimatoraudiofunBigFunLoop.wav:loop=2'
Error initializing complex filters.
No such file or directory
```
Notice the path separators were stripped out...
```
C:UserscarvelAppDataRoamingkinetictextanimatoraudiofunBigFunLoop.wav:loop=2
```
So I tried adding some quotes like:
```
proc.addOption('-filter_complex', `amovie='${data.filepath}:loop=${data.numLoops}'`);
```
and...
```
proc.addOption('-filter_complex', `amovie='${data.filepath}':loop=${data.numLoops}`);
```
and...
```
proc.addOption('-filter_complex', `amovie='${data.filepath}':loop'=${data.numLoops}'`);
```
All 3 generated this exact error...
```
error:  Error: ffmpeg exited with code 1: Error initializing complex filters.
No such file or directory


    at ChildProcess.<anonymous> (C:\Users\carvel\Documents\kinetic-text-animator\build\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
C:\Users\carvel\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:129 stddout
C:\Users\carvel\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:130 stderr ffmpeg version N-83280-gcba4f0e Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 45.100 / 55. 45.100
  libavcodec     57. 75.100 / 57. 75.100
  libavformat    57. 65.100 / 57. 65.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 71.100 /  6. 71.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'C:\Users\carvel\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav':
  Duration: 00:00:15.34, bitrate: 1416 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
[Parsed_amovie_0 @ 000000000248b620] Failed to avformat_open_input 'C'
[AVFilterGraph @ 0000000002496080] Error initializing filter 'amovie' with args 'C:\Users\carvel\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav:loop=2'
Error initializing complex filters.
No such file or directory
```

**Comment by swampthang** [comment]
Realizing that the loop feature isn't available for audio in your library, it occurred to me that, since the amovie filter tells FFMPEG to treat the audio file as a movie, I'd try it again...
```
var bgSettings = data.bgSettings,
    proc;

if ( data.numLoops > 0 && bgSettings.loopBg ) {
  proc = new ffmpeg(data.filepath).loop(data.animationDuration);
  proc.videoFilter('-lavfi');
  proc.addOption('-filter_complex', `amovie='${data.filepath}'`);
} else {
  proc = new ffmpeg(data.filepath);
}
```
Also tried...
```
var bgSettings = data.bgSettings,
    proc = new ffmpeg(data.filepath);

if ( data.numLoops > 0 && bgSettings.loopBg ) {
  proc.videoFilter('-lavfi');
  proc.addOption('-filter_complex', `amovie='${data.filepath}'`);
  proc.loop(data.animationDuration);
}
```
and...
```
var bgSettings = data.bgSettings,
    proc;

if ( data.numLoops > 0 && bgSettings.loopBg ) {
  proc = new ffmpeg(data.filepath)
    .videoFilter('-lavfi')
    .addOption('-filter_complex', `amovie='${data.filepath}'`)
    .loop(data.animationDuration);
} else {
  proc = new ffmpeg(data.filepath);
}
```
These give the same error:
```
error:  Error: ffmpeg exited with code 1: Option loop not found.


    at ChildProcess.<anonymous> (/Users/swampthang/Documents/textanimator/build/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
audio-manager.js:129 stddout 
audio-manager.js:130 stderr ffmpeg version 3.1.1-tessus Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Option loop not found.
```
There seems to be no way of setting up a loop that works in both Mac and PC. Please help if you see I'm missing something. Gotta push this out in a couple of days. Starting to sweat.

**Comment by swampthang** [comment]
Just tried this and it doesn't error but doesn't create the loop
```
var bgSettings = data.bgSettings,
    proc = new ffmpeg(audioFile);

var audioFile = process.platform === 'win32' ? data.filepath.split(':')[1] : data.filepath;

if ( data.numLoops > 0 && bgSettings.loopBg ) {
  proc.videoFilter('-lavfi');
  proc.videoFilter(`amovie=${audioFile}:aloop=${data.numLoops}`);
}
```

**Comment by swampthang** [comment]
Also tried this and doesn't error but doesn't create the looped audio either. As above, it only creates a copy of the input file...
```
if ( data.numLoops > 0 && bgSettings.loopBg ) {
  proc.audioFilters([`aloop=${data.animationDuration}`]);
}
```

**Comment by swampthang** [comment]
Ok, resolved by going in a different direction. Here's a solution that works in Windows and Mac.

In a separate function I'm creating a list.txt file from which I'm doing a concat.
```
// create a list.txt file if loops > 0
if(numLoops > 0) {
  var writeStr = "";
  for ( var i=1; i<=numLoops; i++ ) {
    writeStr += `file '${referenceAudioFile}'\n`;
  }

  fs.writeFile(`${tempFolder}list.txt`, writeStr, 'utf8', (err) => {
    if (err) throw err;
    console.log('list.txt saved');
  });
}
```
So, now, (with some stuff removed to keep it pithy here) we have...
```
function createCompositeAudio(data) {

data.tempAudioFile = `${tempFolder}temp.wav`; // stick a temp.wav file in here.

  var inputFile = data.filepath;

  // read the list.txt file if loops > 0
  if( data.numLoops > 0 && data.bgSettings.loopBg ) {
    inputFile = `${tempFolder}list.txt`;
  }

  var bgSettings = data.bgSettings,
      proc = new ffmpeg(inputFile);

  if( data.numLoops > 0 && data.bgSettings.loopBg ) {
    proc.inputOptions(['-f concat', '-safe 0'])
        .outputOptions('-c copy');
  }

  proc.on('start', function(ffmpegCommand) {
      console.log(`started compositing ${tempFolder}temp.wav`);
  })
  .on('end', function(err, stdout, stderr) {
      returnFile(`${tempFolder}temp.wav`);
  })
  .on('error', function(error,stdout,stderr) {
      /// error handling
      console.log('error: ',error);
      console.log('stddout', stdout);
      console.log('stderr', stderr);
  })
  .output(`${tempFolder}temp.wav`)
  .run();

  function returnFile(filepath) {
    return filepath;
  }
}
```
