### ISSUE TITLE
Random "conversion failed" errors

### ISSUE THREAD

**Issue by geraldoramos** [fluent-ffmpeg/node-fluent-ffmpeg#657]
Hey guys,

I recently started to get random "conversion failed" errors and I wasn't able to identify a pattern. I didn't have any errors like this before and suddenly it started to become frequent.

```
Error: ffmpeg exited with code 1: Conversion failed! 
at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/processor.js:177:22) 
at emitTwo (events.js:106:13) 
at ChildProcess.emit (events.js:191:7) 
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Any ideas on how to troubleshoot this? The error doesn't give any clue on the cause. It is happening to videos or image conversions (at random times during the conversion).

I'm doing Facebook live streams, using images and videos. I also use complexFilters on all of them. 

Any suggestions will be highly appreciated.

**Here is the conversion code from the last crash:**

```
  ffmpeg(image)
            .loop()
            .inputOptions('-re')
            .input('lounge.mp3')
            .flvmeta()
            .format('flv')
            .size('640x360')
            .videoBitrate('300k')
            .videoCodec('libx264')
            .fps(10)
            .audioBitrate('64k')
            .audioCodec('aac')
            .audioFrequency(44100)
            .audioChannels(1)
            .videoFilters({
              filter: 'drawtext',
              options: {
                fontfile: './opensansbold.ttf',
                textfile: '1.txt',
                fontsize: 15,
                fontcolor: '#5f5f5f',
                reload: 1,
                x: 510,
                y: 315
              // shadowcolor: 'silver',
              // shadowx: 2,
              // shadowy: 2
              }
            },
          {
            filter: 'drawtext',
            options: {
              fontfile: './opensansbold.ttf',
              textfile: '2.txt',
              fontsize: 15,
              fontcolor: '#5f5f5f',
              reload: 1,
              x: 68,
              y: 315
            }
          })

            .on('error', function (err) {
              if (ended) {
                endStream('Ended successfully', '2', 'none')
              } else {
                endStream('Ended with error', '2', 'none')
              }

              console.log(err)
              console.log('Task ended with forced error ' + message.token)
              callback()

              setTimeout(function () {
                process.exit(0)
              }, 12000)
            })
            .on('end', function () {
              endStream('Ended successfully', '5', 'Ended after ffmpeg total time or video time', 'none')
              console.log('Task ended successfully after all available period, from user ' + message.token)
              setTimeout(function () {
                process.exit(0)
              }, 12000)
            })
            .save(message.rtmpServer)
```

Regards,

Geraldo

**Comment by njoyard** [comment]
Have you tried reproducing on command line ? If you can, maybe the ffmpeg community will have an idea :/

**Comment by njoyard** [comment]
No further info given, closing
