### ISSUE TITLE
Failing to spawn avprobe

### ISSUE THREAD

**Issue by jacob-cross99** [fluent-ffmpeg/node-fluent-ffmpeg#666]
I've setup my path to work for avpobe/avconv using the following:
```
ffmpeg.setFfmpegPath('./usr/bin/avconv');
ffmpeg.setFfprobePath('./usr/bin/avprobe');
```

but when I run my code, I get the error saying that it failed to spawn avprobe even though I've verified the command executable is there.

> { Error: spawn ./usr/bin/avprobe ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn ./usr/bin/avprobe',
  path: './usr/bin/avprobe',
  spawnargs:
   [ '-show_streams',
     '-show_format',
     '/home/pi/src/lib/profiles/../../public/audio/1.wav' ] }

**Comment by njoyard** [comment]
`ENOENT` means that the file has not been found. ffprobe must not be in `./usr/bin/avprobe` relative to where you execute the program.
