### ISSUE TITLE
Merging Videos Not Working On Heroku Dyno

### ISSUE THREAD

**Issue by bennettl** [fluent-ffmpeg/node-fluent-ffmpeg#678]
I'm trying to merge 2 videos together on an Heroku dyno, but got an error message from the fluent-ffmpeg library.

### Version information

* fluent-ffmpeg version: 2.1.0
* ffmpeg version: git-2013-06-02-5711e4f
* OS: Heroku Dyno

### Code to reproduce

I'm using the buildback on Heroku: https://github.com/shunjikonishi/heroku-buildpack-ffmpeg

```js


const TMP_DIR = '/app/app/services/../tmp/' 

return new Promise((resolve, reject) => {
        ffmpeg(localPath1)
            .input(localPath2)
            .on('error', (err) => {
                logger.error(`'An error occurred: ${err.message}`);
                reject(err)
            })
            .on('end', () => {
                logger.info(`Merging video finished`);
                resolve(localDestPath)
            }).mergeToFile(localDestPath, TMP_DIR);
    })


```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

Two .mov videos merged together

### Observed results

2017-03-16T18:22:52.361442+00:00 app[web.1]: 2017-03-16T18:22:52.360Z - error: 'An error occurred: ffmpeg exited with code 1: 
2017-03-16T18:22:52.368860+00:00 app[web.1]: something's wrong
2017-03-16T18:22:52.370292+00:00 app[web.1]: Error: ffmpeg exited with code 1: 
2017-03-16T18:22:52.370294+00:00 app[web.1]:     at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
2017-03-16T18:22:52.370295+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-03-16T18:22:52.370296+00:00 app[web.1]:     at ChildProcess.emit (events.js:191:7)
2017-03-16T18:22:52.370297+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
