### ISSUE TITLE
Unable to convert h264 video from stream

### ISSUE THREAD

**Issue by FDuros** [fluent-ffmpeg/node-fluent-ffmpeg#724]
#### Archlinux

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.3.2
* OS: Archlinux 4.11.5-1-ARCH

#### Docker alpine-node

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.2.4
* OS: [docker image alpine node 8.1.2](https://hub.docker.com/_/node/)

### Code to reproduce

Two samples:

```js
const fs = require('fs');
const ffmpeg = require('fluent-ffmpeg');

const stream = fs.createReadStream(`video.mp4`);


ffmpeg(stream)
  .videoCodec('libvpx')
  .format('webm')
  .on('end', () => console.log('end conversion'))
  .on('error', (err, stdout, stderr) => {
    console.log(stdout);
    console.error(err);
    console.error(stderr);
  })
  .output('video.webm')
  .run();
```

And one with a pixel format option:

```js
const fs = require('fs');
const ffmpeg = require('fluent-ffmpeg');

const stream = fs.createReadStream(`video.mp4`);
ffmpeg(stream)
  .inputOption('-pix_fmt yuv420p')
  .videoCodec('libvpx')
  .format('webm')
  .on('end', () => console.log('end conversion'))
  .on('error', (err, stdout, stderr) => {
    console.log(stdout);
    console.error(err);
    console.error(stderr);
  })
  .output('video.webm')
  .run();
```
[Link to the video (1MB)](http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4)

### Expected results

I'm expecting the video to be converted to the VP8 codec.

### Observed results

I execute the two samples on two configurations: Archlinux and a docker container. 

I'm trying to encode a H264 video to VP8. 

- It works with video path as input
- The conversion fails with stream as input

#### Archlinux

No error ouput but the converted video has a 0MB size

```
florian@archllama video-converter/sample (develop *%) » node sample.js
end conversion
```

#### Docker container

First sample:

```
/app/sample $ node sample.js 

Error: ffmpeg exited with code 1: Error opening filters!

    at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Alpine 6.3.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libmp3lame --enable-librtmp --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-x11grab --disable-stripping --disable-static --enable-vaapi --enable-libopus --disable-debug
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbd2efb7220] stream 1, offset 0x30: partial file
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbd2efb7220] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 1205 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:0':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    encoder         : Lavf53.24.2
  Duration: 00:00:05.31, bitrate: N/A
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), none, 1280x720, 1205 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 384 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
[buffer @ 0x56113eb0c100] Unable to parse option value "-1" as pixel format
    Last message repeated 1 times
[buffer @ 0x56113eb0c100] Error setting option pix_fmt to value -1.
[graph 0 input from stream 0:0 @ 0x56113eb0c000] Error applying options to the filter.
Error opening filters!
```

Second sample with pixel format option:

```
/app/sample $ node sample.js 

Error: ffmpeg exited with code 1: Option pixel_format not found.

    at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Alpine 6.3.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libmp3lame --enable-librtmp --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-x11grab --disable-stripping --disable-static --enable-vaapi --enable-libopus --disable-debug
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Option pixel_format not found.
```

The first sample works with an [avi video (660k)](http://www.engr.colostate.edu/me/facil/dynamics/files/drop.avi)

Thanks for your time and hard work !

**Comment by njoyard** [comment]
You have to specify input format/codec when using an input stream. Also if you use an input file, don't pass it to fluent-ffmpeg as a stream, pass the filename directly.
