### ISSUE TITLE
Connect to stream, ffmpeg makes 20 connection per second

### ISSUE THREAD

**Issue by MarkM13333** [fluent-ffmpeg/node-fluent-ffmpeg#727]
### Version information

* fluent-ffmpeg version: fluent-ffmpeg 2.x (latest)
* ffmpeg version: 2.8.11
* OS: ubuntu0.16.04.1

I would like to detect silence of a audio stream.
The command in ffmpeg works perfect: `ffmpeg -i http://mystream.com:8000/listen -af silencedetect=n=-50dB:d=0.5 -f null - 2> log.txt`

I made a script with the same conditions, after executing the script, my stream server receiving over 20 connections per second.

My script:
```
var ffmpeg = require('fluent-ffmpeg');
var fs = require('fs');


var output = 'noAudio';
var url ='http://mystream.com:8000/listen';



var command = ffmpeg(url)
  .audioFilters('silencedetect=n=-48dB:d=1')
  .on('error', function(err, stdout, stderr) {
        console.log('Error: ' + err.message);
})
  .on('end', function(stderrLine, stdout, stderr) {
    console.log(stdout); //undefined
    console.log(stderr); //undefined
    console.log("Finished");

})

  .on('start', function(commandLine, stderrLine) {
    console.log('Spawned Ffmpeg with command: ' + commandLine)
})
  .on('stderr', function(stderrLine) {
    console.log('Stderr output: ' + stderrLine);
      if(stderrLine.indexOf('silence_start:') >=0) {
    console.log("Stream is offline");
      if (fs.existsSync(output)) {
           fs.unlinkSync(output)
      }
    } else {
    console.log("Stream is online");
    ffmpeg(url).save(output);
    }

}).save(output)
```

My server doesn't accept more than 20 connections.

Error log:
```
Stream is online
Stderr output:   libavutil      54. 31.100 / 54. 31.100
Stream is online
Stderr output:   libavcodec     56. 60.100 / 56. 60.100
Stream is online
Stderr output:   libavformat    56. 40.101 / 56. 40.101
Stream is online
Stderr output:   libavdevice    56.  4.100 / 56.  4.100
Stream is online
Stderr output:   libavfilter     5. 40.101 /  5. 40.101
Stream is online
Stderr output:   libavresample   2.  1.  0 /  2.  1.  0
Stream is online
Stderr output:   libswscale      3.  1.101 /  3.  1.101
Stream is online
Stderr output:   libswresample   1.  2.101 /  1.  2.101
Stream is online
Stderr output:   libpostproc    53.  3.100 / 53.  3.100
Stream is online
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: http://mystream.com:8000/listen: Server returned 403 Forbidden (access denied)

    at ChildProcess.<anonymous> (/home/myname/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by njoyard** [comment]
That's an issue with your stream server, not with fluent-ffmpeg : `http://mystream.com:8000/listen: Server returned 403 Forbidden (access denied)`

**Comment by MarkM13333** [comment]
No, this happens because of the multiple connections. 
I have a limit of 20 stream connection. 

This module makes connection after connection. 
FFMPEG just one.
