### ISSUE TITLE
output stream no working? 

### ISSUE THREAD

**Issue by psykonaute** [fluent-ffmpeg/node-fluent-ffmpeg#747]
### Version information

* fluent-ffmpeg version:  2.1.2
* ffmpeg version:  @ffmpeg-installer/ffmpeg
* OS: Mac OSX/Unix

### Code to reproduce

```js
	var tempFileName = __dirname+'/../temp/temp'+new Date().getTime()+'.mp4';
var stream = fs.createWriteStream(tempFileName);
	
	var command = ffmpeg(ytdl('https://www.youtube.com/watch?v='+req.params.url,{ filter: function(format) { return format.container === 'mp4'; } , begin:'180s'}))
	    .setDuration('5')
	      .on('progress', function(progress) {
		    console.log('Processing: ' + progress.percent + '% done');
		  })
		 .on('end', function(stdout, stderr) {
		    console.log('Transcoding succeeded !');
		}).output(stream).run()

```
### Expected results
If I replace output(stream) with output('outputFile.mp4') it does work fine. 
But as soon as I put a stream I get such error: 
`Error: ffmpeg exited with code 1: pipe:1: Invalid argument

    at ChildProcess.<anonymous> (/Users/psykomatt/Dropbox (Personal)/Documents/workspace/Emoticast/Tunemoji-Web/functions/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
`

**Comment by IvanMMM** [comment]
Same here
```js
      var stream  = fs.createWriteStream(path.join(__dirname,'/videos/watermarked.mp4'));

      ffmpeg()
      .input(path.join(__dirname,'/videos/SampleVideo_1280x720_2mb.mp4'))
      .input(path.join(__dirname,'/test/mark.png'))
      .complexFilter([
           {
              inputs:['1'],
              filter:'scale',
              options:`w=${newImageSize.w}:h=${newImageSize.h}`,
              outputs:'overlayRescaled'
           },
           {
              inputs:['0','overlayRescaled'],
              filter:'overlay',
              options:`x=${positions.x}:y=${positions.y}`
           }
       ])
       .stream(stream,{end:true})
```

**Comment by IvanMMM** [comment]
Oh, we just need to set output format and codecs.

```js
            .audioCodec('aac')
            .videoCodec('libx264')
            .format('avi')
            .output(stream,{end:true})
```
Unfortunately, looks like there's no way to pipe mp4 to stream :(

**Comment by njoyard** [comment]
There's a bunch of codec-specific options that make the format streamable, you should look in the ffmpeg docs

**Comment by IvanMMM** [comment]
@njoyard, this all codec-stuff is a whole new word for me. So it will be easier just to write temp file for now and read it after . But thank you for your direction.

**Comment by gagangoku** [comment]
@IvanMMM Thanks for the tip. Took me a while to figure out, but missing the output format in the command and ffmpeg throws the vague error

**Comment by tymmesyde** [comment]
> Unfortunately, looks like there's no way to pipe mp4 to stream :(

@IvanMMM
This will allow you to pipe mp4 to a stream
(It will not produce a seekable stream however)
```js
ffmpeg()
    .input(fileStream)
    .videoCodec('libx264')
    .audioCodec('aac')
    .outputFormat('mp4')
    .outputOptions([
        '-movflags frag_keyframe+empty_moov'
    ])
    .pipe(writeStream, { end: true });
```
