### ISSUE TITLE
Error: ffmpeg exited with code 1: Error reinitializing filters!

### ISSUE THREAD

**Issue by shuiRong** [fluent-ffmpeg/node-fluent-ffmpeg#809]
### Version information

* fluent-ffmpeg version: ^2.1.0
* ffmpeg version: 3.4.2
* OS: OSX 10.13.3 (Sierra)

### Code to reproduce

```js
let result = app.command(event.template,event.filters).fps(6.5).size('60%').videoBitrate(280).save(filePath)
console.log('ok until here!')

result.on('end', function (a, b, c) {
      console.log('Convert Success')     
})
```

I typed this 
`ffmpeg -i templates/input.mp4 output.gif`
it's fine for `output.gif`

### Expected results

I am not sure, because it's some open source project's code.

### Observed results

```
ok until here!
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: Error reinitializing filters!
Failed to inject frame into filter network: No such file or directory
Error while processing the decoded data for stream #0:0
Conversion failed!

    at ChildProcess.<anonymous> (/Users/shuirong/Code/dongtu-function/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

**Thank you in advance**

---

**Update**

I print the command that was executed by node.js: 
```
ffmpeg -i /Users/shuirong/Code/dongtu-function/templates/wangjingze.mp4 -y -an -filter:v drawtext=text=saaaaaaaaaaaaaaaaaaaaa:x=(w-text_w)/2:y=(h-text_h)/2:fontfile=/Users/shuirong/Code/dongtu-function/fonts/STHeiti.ttf:fontcolor=white:fontsize=24,drawtext=text=ffff:x=(w-text_w)/2:y=(h-text_h)/2:enable='between(t,2,3)':fontfile=/Users/shuirong/Code/dongtu-function/fonts/STHeiti.ttf:fontcolor=white:fontsize=24,drawtext=text=动图生成dongtu666.com:x=(w-text_w)-5:y=5:fontfile=/Users/shuirong/Code/dongtu-function/fonts/STHeiti.ttf:fontcolor=white@0.45:fontsize=24 output.gif
```
and then execute it in the command line.
Unfortunately，some error was thorwed:
```
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/include/darwin' --host-ldflags= --disable-jack --enable-gpl --enable-chromaprint --enable-ffplay --enable-frei0r --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopus --enable-librtmp --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzmq --enable-opencl --enable-videotoolbox --enable-openssl --enable-lzma --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3 --enable-nonfree
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/shuirong/Code/dongtu-function/templates/wangjingze.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2018-02-26T16:53:36.000000Z
    encoder         : HandBrake 1.0.7 2017040900
  Duration: 00:00:07.20, start: 0.000000, bitrate: 295 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/bt709), 720x480 [SAR 32:27 DAR 16:9], 291 kb/s, 25 fps, 25 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2018-02-26T16:53:36.000000Z
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> gif (native))
Press [q] to stop, [?] for help
[Parsed_drawtext_0 @ 0x7feef4682b60] Using "/Library/Fonts/Arial Unicode.ttf"
**[drawtext @ 0x7feef49e8600] [Eval @ 0x7ffeece48080] Missing ')' or too many args in 'between(t'
[drawtext @ 0x7feef49e8600] Error when evaluating the expression 'between(t' for enable
[AVFilterGraph @ 0x7feef4705720] Error initializing filter 'drawtext' with args 'text=ffff:x=(w-text_w)/2:y=(h-text_h)/2:enable=between(t'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!**
```

**Comment by njoyard** [comment]
1. set an 'error' handler
2. don't set event handlers after calling save(), always do that *before* (save can raise events synchronously)
3. your filter chain is probably wrong, as hinted by the ffmpeg errors, please solve the ffmpeg usage problem first and then try to replicate it with fluent-ffmpeg

**Comment by Satvik3799** [comment]
I have a similar error in my Windows 10 version. What should I do?
