### ISSUE TITLE
Error: ffmpeg exited with code 1: Conversion failed!

### ISSUE THREAD

**Issue by mayankvolansys** [fluent-ffmpeg/node-fluent-ffmpeg#816]
### Version information

* fluent-ffmpeg version: "fluent-ffmpeg": "^2.1.2",
* ffmpeg version: 
* OS: Linux

### Code to reproduce

```js

Error: ffmpeg exited with code 1: Conversion failed!

    at ChildProcess.<anonymous> (/opt/incident/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
Error: ffmpeg exited with code 1: Conversion failed!

    at ChildProcess.<anonymous> (/opt/incident/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
Completed the incident processing.
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24):

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Checklist

* [ ] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
There's no way we can do anything to help if you don't show the code and respect the checklist !

**Comment by gvsro** [comment]
@mayankvolansys Can you give us more info?

**Comment by mayankvolansys** [comment]
Resolved this issue using, 
I am using Thumbler lib for converting images and Thumber lib in backed using ffmpeg having the issue in when we pass file path with the extra character like ( "(", ")" ) and using the quote I am solving this issue.
Thanks
