### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sergibondarenko** [fluent-ffmpeg/node-fluent-ffmpeg#852]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 1.0.15
* OS: Ubuntu 18.04.1

### Code to reproduce

```js
const fs = require('fs');
const path = require('path');
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;
const ffprobePath = require('@ffprobe-installer/ffprobe').path;
const ffmpeg = require('fluent-ffmpeg');
ffmpeg.setFfmpegPath(ffmpegPath);
ffmpeg.setFfprobePath(ffprobePath);

const videoFolder = path.resolve('videos/bad_converted');
const finalVideo = path.resolve('final_video.mp4');
const configFile = path.resolve('concat_config.txt'); 

// main
let videos = fs.readdirSync(videoFolder).map(file => path.join(videoFolder, file));
fs.writeFileSync(configFile, videos.map(file => `file ${file}\n`).join(''));
  
const mpeg = ffmpeg();
mpeg.input(configFile)
  .inputOptions(['-f concat', '-safe 0'])
  .outputOptions('-c copy')
  .save(finalVideo);
```

Config file
```
trex@cave:/media/trex/safe1/Development/app$ head concat_config.txt 
file /media/trex/safe1/Development/app/videos/bad_converted/APEST - THE CARTERS.mp4
file /media/trex/safe1/Development/app/videos/bad_converted/ASAP_Rocky_ASAP_Forever_ft_Moby.mp4
```

### Expected results
Concatenate all files inside `videoFolder` using `configFile` and create final_video.mp4.

### Observed results
```
trex@cave:/media/trex/safe1/Development/app$ node test_concat_video.js 
/media/trex/safe1/Development/app/concat_config.txt
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: /media/trex/safe1/Development/app/concat_config.txt: No such file or directory

    at ChildProcess.<anonymous> (/media/trex/safe1/Development/app/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

But the config exists and my user has write permission
```
trex@cave:/media/trex/safe1/Development/app$ ls -lh concat_config.txt 
-rw-r--r-- 1 trex trex 3,7K ott  8 19:47 concat_config.txt
trex@cave:/media/trex/safe1/Development/app$ whoami 
trex
```

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by sergibondarenko** [comment]
I noticed that the error is thrown when I try to convert videos in `bad` folder
```
trex@cave:/media/trex/safe1/Development/app/videos/bad$ ls -lh ../bad
total 1,3G
-rw-r--r-- 1 trex trex 36M set 16 09:50 Action_Bronson_The_Chairman_s_Intent.mp4
-rw-r--r-- 1 trex trex 39M set 16 09:51 APEST___THE_CARTERS.mp4
-rw-r--r-- 1 trex trex 53M set 16 09:56 ASAP_Rocky_ASAP_Forever_ft_Moby.mp4
-rw-r--r-- 1 trex trex 30M set 16 13:47 Beck___Up_All_Night.mp4
-rw-r--r-- 1 trex trex 30M set 16 09:57 Blood_Orange___Charcoal_Baby__Official_Video_.mp4
-rw-r--r-- 1 trex trex 27M set 16 09:59 Blood_Orange___Saint__Official_Video_.mp4
-rw-r--r-- 1 trex trex 55M set 16 09:58 Charlotte_Gainsbourg___Deadly_Valen
```

There is no error with `geo` folder
```
trex@cave:/media/trex/safe1/Development/app/videos/bad$ ls -lh ../geo
total 1,4G
-rw-r--r-- 1 trex trex  90M set 16 14:02 417912400.mp4
-rw-r--r-- 1 trex trex 254M set 16 13:58 440386842.mp4
-rw-r--r-- 1 trex trex 135M set 16 14:12 443232498.mp4
-rw-r--r-- 1 trex trex  36M set 16 13:59 469090821.mp4
```

Probably node-fluent-ffmpeg doesn't like underscore or soething else about files in `bad` folder.

**Comment by sergibondarenko** [comment]
My solution was to replace all special chars to underscore using rename
```
rename -n 's/[ @\$\-\(\),]/_/g' *
```

Now it works with file names like these
```
trex@cave:/media/trex/safe1/Development/fonotv-2.0/videos/bad_converted$ ls -lh
total 1011M
-rw-r--r-- 1 trex trex  21M ott  7 20:09 Action_Bronson_The_Chairman_s_Intent.mp4
-rw-r--r-- 1 trex trex 2,1K ott  8 18:21 APEST___THE_CARTERS.mp4
-rw-r--r-- 1 trex trex  27M ott  7 20:07 ASAP_Rocky_ASAP_Forever_ft_Moby.mp4
-rw-r--r-- 1 trex trex  30M ott  7 20:10 Beck___Up_All_Night.mp4
```

**Comment by govindrai** [comment]
None of my files any special characters, and node_fluent will try this error, almost every other execution. I am use node-fluent with cypress to record our automation tests:

```
  Running:  smokescreen/auth/collaboration.spec.js                                         (3 of 10)
  Estimated: 1 minute, 4 seconds
[cypress-log-to-output] Attempting to connect to Chrome Debugging Protocol
[cypress-log-to-output] Connected to Chrome Debugging Protocol


  Auth - Collaboration
Incoming Request: GET /bundle/vendor.js
Incoming Request: GET /bundle/app.js
Incoming Request: GET /images/beautifulai-logos/beautifulai-logo-reverse.svg
Incoming Request: GET /images/auth/google.svg
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: /workspace/cypress/videos/smokescreen/auth/collaboration.spec.js.mp4: No such file or directory

    at ChildProcess.<anonymous> (/root/.cache/Cypress/5.4.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: /workspace/cypress/videos/smokescreen/auth/collaboration.spec.js.mp4: No such file or directory

    at ChildProcess.<anonymous> (/root/.cache/Cypress/5.4.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: /workspace/cypress/videos/smokescreen/auth/collaboration.spec.js.mp4: No such file or directory

    at ChildProcess.<anonymous> (/root/.cache/Cypress/5.4.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

**Comment by vikram-sapate** [comment]
This happens when ffmpeg can't access the particular folder. 

This permission error occurred with me when I cloned github repo. on linux server.

After some time I deleted that repo and used FileZilla to connect to instance & transferred all files and folders.

And it worked for me.

**Comment by CodingMeSwiftly** [comment]
For me, the issue was providing ffmpeg with relative paths. Changing to absolute paths (`process.cwd()/...`) fixed the issue.

**Comment by tigermax139** [comment]
For me, same thing happens when I tried to take a screenshot but timer seconds was greater than total video duration
