### ISSUE TITLE
NodeJS process crash when killing ffmpeg instance

### ISSUE THREAD

**Issue by Ekliptor** [fluent-ffmpeg/node-fluent-ffmpeg#861]
* fluent-ffmpeg version: 2.1.2
* ffmpeg version: ffmpeg static 2.3 from https://www.npmjs.com/package/ffmpeg-static
* OS: Debian 9

I am using ffmpeg for screenshot generation and video transcoding on many servers. Sometimes a task doesn't finish, so I added a code to abort it using `setTimeout()`

```js
let commandObj = FfmpegCommand(..);
setTimeout(() => {
     commandObj.kill("SIGKILL");
}, 10000);

```

This works 99% of the time, however sometimes I get crashes with stacktraces telling me that stdErr is undefined
```
TypeError: Cannot read property 'get' of undefined", "    at endCB (/home/staydown/nodejs/SD_Inspector/SpiderManager/node_modules/fluent-ffmpeg/lib/processor.js:544:37)", "    at ChildProcess.<anonymous> (/home/staydown/nodejs/SD_Inspector/SpiderManager/node_modules/fluent-ffmpeg/lib/processor.js:159:9)", "    at ChildProcess.emit (events.js:182:13)", "    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)", "    at onErrorNT (internal/child_process.js:406:16)", "    at process._tickCallback (internal/process/next_tick.js:63:19)"
```

Since the lines above 159 already check for process exit, I suggest adding a check if stdErr is undefined or a try-catch.

**Comment by njoyard** [comment]
Oh actually I think we're just missing the stdoutRing/stderrRing arguments on line 159 :confused:

**Comment by ocramot** [comment]
I stumpled upon the same problem today and I made a simple fix for it: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/883

**Comment by Birowsky** [comment]
This happens in my aws lambda, no idea what causes it. If anyone could share a workaround, I'd really appreciate it.

**Comment by mustafa-colakoglu** [comment]
> This happens in my aws lambda, no idea what causes it. If anyone could share a workaround, I'd really appreciate it.

Solved with : https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/935

**Comment by dank074** [comment]
Also ran into this problem. It is some type of race condition that occurs when you add an output before adding event listeners in ffmpeg command builder.

This triggered the exception on process kill:
```typescript
const command = ffmpeg(input)
                .output(ffmpegOutput)
                .on('end', () => {
                    console.log("video ended")
                });
command.run();
```

But this did not cause any exceptions when killing the process:
```typescript
const command = ffmpeg(input)
                .on('end', () => {
                    console.log("video ended")
                })
               .output(ffmpegOutput);
command.run();
```
