### ISSUE TITLE
FFMPEG pipe stream to S3 pre-signed PUT URL.

### ISSUE THREAD

**Issue by xoraingroup** [fluent-ffmpeg/node-fluent-ffmpeg#925]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 4.1.3
* OS: Mac OS X 10.14.5

### Code to reproduce

```js
const ffmpeg = require('fluent-ffmpeg');
const request = require('request');

const video = '/Users/xorain/Documents/test_videos/movie.mp4';
const putURL = 'https://some-aws-signed-put-url/videos-bucket-nurm/219/219-1564216171442-6dfd8c309a25fa9779fa7164acd35221f1c4301d3a037e297456637c236ee9da.mp4?X-Amz-Meta-Uid=219&X-Amz-Meta-Sub=614505702013204&X-Amz-Meta-Vid=2604&X-Amz-Meta-Ofn=movie.mp4&X-Amz-Meta-Region=eu-nurm-de&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190727%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190727T082931Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=79243c973634d0fee5d54c0f6c99e7fb657e425553e2281bf0aa4d01186b49ea';

const outputPipe = ffmpeg(video, {logger: console})
    .audioCodec('copy')
    .videoCodec('copy')
    .outputOptions([
         '-movflags frag_keyframe+empty_moov',
         '-movflags +faststart'
     ])
    .toFormat('mp4')
    .on('start', (cmd) => {
        console.info(cmd)
    })
    .on('error', (error) => {
        console.info(error)
    })
    .on('end', () => {
        console.info('finished uploading')
    })
    .pipe(request.put(putURL))
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
The stream should be piped to amazon AWS put url.

### Observed results
Error: You cannot pipe to this stream after the outbound request has started.
    at Request.<anonymous> (/usr/local/lib/node_modules/request/request.js:495:26)
    at Request.emit (events.js:198:13)
    at Socket.Readable.pipe (_stream_readable.js:742:8)
    at processCB (/Users/xorain/Git/personal/ffmpeg-logging/node_modules/fluent-ffmpeg/lib/processor.js:480:31)
    at /Users/xorain/Git/personal/ffmpeg-logging/node_modules/fluent-ffmpeg/lib/processor.js:213:7
    at FfmpegCommand.proto._getFfmpegPath (/Users/xorain/Git/personal/ffmpeg-logging/node_modules/fluent-ffmpeg/lib/capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (/Users/xorain/Git/personal/ffmpeg-logging/node_modules/fluent-ffmpeg/lib/processor.js:132:10)
    at /Users/xorain/Git/personal/ffmpeg-logging/node_modules/fluent-ffmpeg/lib/processor.js:437:12
    at /Users/xorain/Git/personal/ffmpeg-logging/node_modules/async/dist/async.js:473:16
    at next (/Users/xorain/Git/personal/ffmpeg-logging/node_modules/async/dist/async.js:5329:29)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Request.onerror (_stream_readable.js:717:7)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/request/request.js:495:12)
    at Request.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at FfmpegCommand.proto._spawnFfmpeg (/Users/xorain/Git/personal/ffmpeg-logging/node_modules/fluent-ffmpeg/lib/processor.js:132:10)

### Checklist

* [X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [X] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

I would like to know if its possible to directly pipe the output stream to a signed put url?? Just curious to know. Thank you

**Comment by Mat-thieu** [comment]
Hi I could be mistaken, but I feel like request.put() does not actually return a stream you can write to. You have to make sure the request becomes a stream input and the request library knows it should return an input.

I did a quick google search but couldn't find a quick solution, maybe you will have more luck.
Let me know if it worked!

**Comment by RamK777** [comment]
@Mat-thieu  Did you got the solution ?

**Comment by lemonScaletech** [comment]
@xoraingroup hey, were you able to solve this ?

**Comment by rabeetcarma** [comment]
any hope on the solution?

**Comment by gulshan-dev123789** [comment]
> @Mat-thieu Did you got the solution ?

any solution how to sream output to bucket ?

**Comment by Mat-thieu** [comment]
I don't have a solution, I only remember `request` doesn't provide what you need here. It won't give you a writable stream.

Instead you can consider using the https package in node, which should return you a writable stream according to the docs
https://nodejs.org/api/https.html#httpsrequestoptions-callback

probably looks something like this, but I didn't test it fully
```javascript
const https = require('https');
const { URL } = require('url');

const putURL = new URL('https://upload-url');

const options = {
    hostname: putURL.hostname,
    path: putURL.pathname + putURL.search,
    method: 'PUT',
    headers: {
        'Content-Type': 'video/mp4',
    },
};

console.log(options);

// creates a writable stream
const req = https.request(options, (res) => {
    res.on('data', (chunk) => {
        console.log(`BODY: ${chunk}`);
    });
    res.on('end', () => {
        console.log('No more data in response.');
    });
});

req.on('error', (e) => {
    console.error(`error`, e);
});
```

then you can pipe the request to ffmpeg

```javascript
ffmpeg(video)
   // your operations
    .on('error', (error) => {
        console.error(`ffmpeg error: ${error}`);
        req.end();
    })
    .on('end', () => {
        console.info('ffmpeg processing finished, finishing upload...');
        req.end();
    })
    .pipe(req, { end: false });
```

**Comment by alpacaPwaa** [comment]
@Mat-thieu Hi, I tested your idea.

```
const putObjectCommand = new PutObjectCommand({
        Bucket: process.env.AWS_BUCKET_NAME!,
        Key: generateFileName(),
      });

      const s3 = new S3Client({
        region: process.env.AWS_BUCKET_REGION!,
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY!,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
        },
      });

      const singedURL = await getSignedUrl(s3, putObjectCommand, {
        expiresIn: 60,
      });

      const ffmpeg = require("fluent-ffmpeg");
      const https = require("https");
      const { URL } = require("url");

      const putURL = new URL(singedURL);

      const options = {
        hostname: putURL.hostname,
        path: putURL.pathname + putURL.search,
        method: "PUT",
        headers: {
          "Content-Type": "video/mp4",
        },
      };

      const req = https.request(options, (res: IncomingMessage) => {
        res.on("data", (chunk: Buffer) => {
          console.log(`BODY: ${chunk}`);
        });
        res.on("end", () => {
          console.log("No more data in response.");
        });
      });

      req.on("error", (e: Error) => {
        console.error(`error`, e);
      });

      ffmpeg()
        .input(input.video)
        .on("end", () => {
          console.log("Job done");
          req.end();
        })
        .on("error", (error: string) => {
          console.error("Error:", error);
          req.end();
        })
       // operations
        .videoCodec("libx264")
        .outputFormat("mp4")
        .outputOptions(["-movflags frag_keyframe+empty_moov"])
        .pipe(req, { end: false });
```
        
And it gave an error like this,

       ```
 BODY: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Header>Transfer-Encoding</Header><RequestId>558HFCHAMQCTJCCN</RequestId><HostId>4/D/xcV/cmlGaElaThiE4Z+HShtp1zIyZXRPDqSS4DDG6qsVqbUM4vo+kD8RvVQlntVlC961CGHx6H1oOBP8AA==</HostId></Error>
No more data in response.
Error: Error: Output stream closed
    at Timeout.eval [as _onTimeout] (webpack-internal:///(rsc)/./node_modules/fluent-ffmpeg/lib/processor.js:491:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
