### ISSUE TITLE
Always get errors when trying to pipe to a stream

### ISSUE THREAD

**Issue by oonqt** [fluent-ffmpeg/node-fluent-ffmpeg#967]
### Version information

* fluent-ffmpeg version: 2.2
* ffmpeg version: 3.4.6
* OS: Ubuntu 18.04

### Code to reproduce

```js
ffmpeg()
	.input(streamToReadable(req.file.buffer))
	.videoCodec("libx264")
	.audioCodec("libmp3lame")
	.audioChannels(2)
	.audioBitrate(128)
	.videoBitrate(300)
	.toFormat("mp4")
	.pipe(res, { end: true })
```
### Expected results

Expected the output to be piped into response

### Observed results

I noticed that this will work with the same settings if i omit the "pipe" and instead save it directly to a file

Outputs with: `Error: ffmpeg exited with code 1: Conversion failed!

    at ChildProcess.<anonymous> (/home/home/code-server-projects/memester-server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at emitEnd (/home/home/code-server-projects/memester-server/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/home/home/code-server-projects/memester-server/node_modules/fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/home/home/code-server-projects/memester-server/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at ChildProcess.<anonymous> (/home/home/code-server-projects/memester-server/node_modules/fluent-ffmpeg/lib/processor.js:182:11)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)`

**Comment by blex41** [comment]
Did you find a solution? I'm having the same problem in this environment:

- fluent-ffmpeg version: 2.1.2
- ffmpeg version: git-2019-12-26-b0d0d7e
- OS: Windows 10

Saving to a file works fine, though

**Comment by MrShakhov** [comment]
+1

**Comment by ardalann** [comment]
+1
When I try to output an mp4 to a stream, I get the following error:
```
ffmpeg exited with code 1: Could
 not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!
```
When I change the format to avi, it works. So it's clear it has something to do with the output format. I can't use avi in my use-case though because the file size would be 4 times bigger than mp4.

**Comment by Coriou** [comment]
Same issue, I switched to using FFmpeg directly rather than using this lib which did create a lot of puzzling bugs like this one.

Quick tip: you can use the this library to generate the command, and then just run it directly using node's child process

**Comment by ingageco** [comment]
I had the same issue, and mine had to do with the output codec for audio. The file was in MP3, and I needed to explicitly set it to AAC before it would stream. My recommendation is to try to run the same command directly in ffmpeg, and see if there are any errors.

**Comment by felix-lunii** [comment]
based on https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/802#issuecomment-366469595 && https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/915#issuecomment-506665957 , It seems that you need to specify the output format using  the `format()` method

**Comment by Coriou** [comment]
@felix-lunii The alias `toFormat` used in the snippet provided works the same as `format` (thus why it's called an alias)

I think, in this case, that it's possible some of the headers are probably written to the `res` stream, and that's the problem. Please check that you're not writing a HTTP status code or something else to the stream before FFMPEG.

Try this and please report back if it was the issue.

**Comment by michaelshum** [comment]
Has this been resolved? I've been running into the same issue (nothing written to res stream before running ffmpeg commands), and the same commands work perfectly when saving to file like this

```
var proc = ffmpeg(path);
proc.setStartTime(duration)
  .addInput('./in.mp3')
  .output('out.mp4')
  .run();
```
whereas piping the same thing to res
```
proc.setStartTime(duration)
  .addInput('./in.mp3')
  .format('mp4')
  .pipe(res, {end: true});
```
fails with `Error: ffmpeg exited with code 1: Conversion failed!`

**Comment by Coriou** [comment]
Add a `.logger(console)` and see if you get more details on the error.

Or please make a repro repository so I can check it out myself.

**Comment by Nerixyz** [comment]
@michaelshum Your issue is `.format('mp4')`. See #346

**Comment by lemonnn-8** [comment]
You have to use output options as you are using stream. try adding
`.outputOptions('-movflags frag_keyframe+empty_moov')`

**Comment by OmarBakr2020** [comment]
Hey @lemonnn-8 I have the same problem when uploading the mp4 stream to AWS s3, But it isn't converted. Can you help me?

`let readstream = s3.getObject(params).createReadStream();
  console.log(readstream);
  ffmpeg.setFfmpegPath(ffmpegPath);

  const ffmpegProcess = ffmpeg(readstream);

  ffmpegProcess
    .outputOptions('-movflags frag_keyframe+empty_moov')
    .format('mp4')
    .on('error', (err, stdout, stderr) => {
      // Handle errors here
      console.log(err);
      console.log(err.message);
    })
    .on('end', () => {
      // Processing is complete
      console.log('Processing finished !');
    })
    .save(`${response.Key}.mp4`)
    .pipe(uploadToS3(response.Key, response.Bucket));
}

const uploadToS3 = (key: string, bucket: string) => {
  // Create a new stream
  let pt = new stream.PassThrough();

  // Reuse the same params object and set the Body to the stream
  let params = {
    Bucket: bucket,
    Key: key,
    Body: pt,
  };

  // Upload and wait for the result
  s3.upload(params, (err: Error, data: any) => {
    if (err) return console.error(err);

    console.log('done');
    console.log(data.Location);
  });

  return pt;
};`

**Comment by Ryuytyuu-Greseven** [comment]
> You have to use output options as you are using stream. try adding `.outputOptions('-movflags frag_keyframe+empty_moov')`

@lemonnn-8  Browsed and Tried plenty of solutions, but finally this worked. 🎞️🎥🎬🍿🍿

**Comment by LionByteTech** [comment]
> You have to use output options as you are using stream. try adding `.outputOptions('-movflags frag_keyframe+empty_moov')`

I have been battling this issue for Firebase Storage On Trigger for weeks now!! This did it! The only thing i was missing! Lets go! thank you!

**Comment by qwerty4882** [comment]
my express server works with

`const readStream = file.createReadStream({ start, end })
readStream.pipe(res)
`
but not work with

`const readStream = file.createReadStream({ start, end })
ffmpeg(readStream).format('h264').pipe(res)`

complete function


`
const streamfunction = (torrent, req, res) => {
  lastRunningStreamsTimeOut[torrent.infoHash] = new Date()

  const file = torrent.files[0]

  const fileLength = file.length
  const range = req.headers.range
  if (!range) {
    res.status(406).status('accces denies')
  } else {
    const CHUNK_SIZE = 10 ** 6 //1MB
    const start = Number(range.replace(/\D/g, ''))
    const end = Math.min(start + CHUNK_SIZE, fileLength - 1)
    const contentLength = end - start + 1
    const headers = {
      'Content-Range': `bytes ${start}-${end}/${fileLength}`,
      'Accept-Ranges': 'bytes',
      'Content-Length': contentLength,
      'Content-Type': 'video/mp4',
    }
    res.writeHead(206, headers)

    const readStream = file.createReadStream({ start, end })

    ffmpeg(readStream).format('h264').pipe(res)
    // readStream.pipe(res)
  }
}`
error

`Error: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input

    at ChildProcess.<anonymous> (C:\code\projects\video stream\server\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (C:\code\projects\video stream\server\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at endCB (C:\code\projects\video stream\server\node_modules\fluent-ffmpeg\lib\processor.js:544:13)
    at handleExit (C:\code\projects\video stream\server\node_modules\fluent-ffmpeg\lib\processor.js:170:11)
    at ChildProcess.<anonymous> (C:\code\projects\video stream\server\node_modules\fluent-ffmpeg\lib\processor.js:182:11)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

Node.js v18.13.0
[nodemon] app crashed - waiting for file changes before starting...`



please help if anyone know about it

**Comment by OdapX** [comment]
> You have to use output options as you are using stream. try adding `.outputOptions('-movflags frag_keyframe+empty_moov')`

Thank you !
