### ISSUE TITLE
Can't fit generation command "-f lavfi"

### ISSUE THREAD

**Issue by polisen** [fluent-ffmpeg/node-fluent-ffmpeg#974]
### Version information

* fluent-ffmpeg version: "^2.1.2"
* ffmpeg version: 4.2.1
* OS: OSX Mojave

### Code to reproduce

I am trying to fit this command into fluent-ffmpeg but I just can't figure it out.
ffmpeg -f lavfi -i anullsrc=r=16000 -t 60 -acodec pcm_s16le out.wav

I don't understand where to fit the "-f lavfi" part of it. I understand that this is just another way to initiate a complex filter but I'm really just drawing blanks on how to solve it.

```js

async function generate_silence(){
ffmpeg(`-i anullsrc=r=16000`).outputOptions(['-t 60', '-acodec pcm_s16le']).save(`./test.wav`);
}

generate_silence();
```

### Expected results

1 minute of generated silence in .wav format

### Observed results
Obviously none - the problem being the missing "-f lavfi"

```(node:5101) UnhandledPromiseRejectionWarning: Error: No input specified
    at FfmpegCommand.proto.addInputOption.proto.addInputOptions.proto.withInputOption.proto.withInputOptions.proto.inputOption.proto.inputOptions (/Users/fredrikwesterdahl/Projects/bleeper/node_modules/fluent-ffmpeg/lib/options/custom.js:43:13)
    at generate_silence (/Users/fredrikwesterdahl/Projects/bleeper/functions/bleep_engine_2.js:4:46)
    at Object.<anonymous> (/Users/fredrikwesterdahl/Projects/bleeper/functions/bleep_engine_2.js:44:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11
(node:5101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by bwagner** [comment]
Try:
```
ffmpeg('anullsrc=r=16000').inputFormat('lavfi').outputOptions(['-t 60', '-acodec pcm_s16le']).save('./test.wav').run()
```
([inspiration](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/557))
