### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by RHeijnen** [fluent-ffmpeg/node-fluent-ffmpeg#997]
### Version information

* fluent-ffmpeg version: fluent-ffmpeg@2.1.2
* ffmpeg version: Build: ffmpeg-20200413-59e3a9a-win64-static
* OS: WIN 10 (latest)

### Code to reproduce
Your own merge example

### Expected results

A merged file.

### Observed results
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (C:\Users\*\Documents\GitHub\*\__workspace\youtubething\node_modules\request\request.js:816:19)
    at Object.onceWrapper (events.js:417:28)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
    at Object.onceWrapper (events.js:417:28)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.Socket._onTimeout (net.js:478:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on Readable instance at:
    at Readable.onevent (C:\Users\*\Documents\GitHub\*\__workspace\youtubething\node_modules\streamify\lib\index.js:128:17)
    at Readable.emit (events.js:311:20)
    at Request.emit (events.js:311:20)
    at ClientRequest.<anonymous> (C:\Users\*\Documents\GitHub\*\__workspace\youtubething\node_modules\request\request.js:819:16)
    at Object.onceWrapper (events.js:417:28)
    [... lines matching original stack trace ...]
    at TLSSocket.Socket._onTimeout (net.js:478:8) {
  code: '**ESOCKETTIMEDOUT**',
  connect: false
}

**Comment by arulananth** [comment]
Same issues.
